[workspace]
resolver = "2"
members = [
    "crates/aura-ast",
    "crates/aura-diagnostics",
    "crates/aura-analysis",
    "crates/aura-lexer",
    "crates/aura-parser",
    "crates/aura-sema",
    "crates/aura-ownership",
    "crates/aura-hir",
    "crates/aura-mir",
    "crates/aura-ir",
    "crates/aura-codegen",
    "crates/aura-package",
    "crates/aura-cli",
    "crates/aura-lsp",
]
default-members = ["crates/aura-cli"]

[workspace.package]
version = "0.1.1-alpha.8"
edition = "2021"
license = "MIT"
repository = "https://github.com/auraspace/aura"
rust-version = "1.80"

[workspace.dependencies]
aura-ast = { path = "crates/aura-ast" }
aura-diagnostics = { path = "crates/aura-diagnostics" }
aura-analysis = { path = "crates/aura-analysis" }
aura-lexer = { path = "crates/aura-lexer" }
aura-parser = { path = "crates/aura-parser" }
aura-sema = { path = "crates/aura-sema" }
aura-ownership = { path = "crates/aura-ownership" }
aura-hir = { path = "crates/aura-hir" }
aura-mir = { path = "crates/aura-mir" }
aura-ir = { path = "crates/aura-ir" }
aura-codegen = { path = "crates/aura-codegen" }
aura-package = { path = "crates/aura-package" }
