/* Aura runtime translation unit. Implementation is organized by subsystem. */

#include "src/preamble.c"
#include "src/core.c"
#include "src/io_file.c"
#include "src/io_tcp.c"
#include "src/io_udp.c"
#include "src/io_websocket.c"
#include "src/http_parser.c"
#include "src/http_response.c"
#include "src/http_connection.c"
#include "src/stdlib_io_fs.c"
#include "src/exceptions.c"
#include "src/gc_ownership.c"
#include "src/ffi.c"
#include "src/abi_race.c"
#include "src/task_frame.c"
#include "src/task_executor.c"
#include "src/io_operations.c"
#include "src/task_channel.c"
#include "src/process.c"
