[package]
name = "aura-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[dependencies]
aura-lexer = { path = "../crates/aura-lexer" }
aura-parser = { path = "../crates/aura-parser" }
aura-package = { path = "../crates/aura-package" }
libfuzzer-sys = "0.4"

[[bin]]
name = "lexer"
path = "fuzz_targets/lexer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "manifest"
path = "fuzz_targets/manifest.rs"
test = false
doc = false
bench = false

[[bin]]
name = "lockfile"
path = "fuzz_targets/lockfile.rs"
test = false
doc = false
bench = false
