//! Top-level C translation unit emission.

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use aura_ast::*;
use aura_sema::{CheckedFile, Ty};

use crate::array_emit::{emit_array_mono, is_array_mono, is_array_type_key};
use crate::class_emit::*;
use crate::ctx::{EmitCtx, EmitOptions};
use crate::enum_emit::*;
use crate::expr::{
    bounded_spawn_captures, bounded_spawn_destroy_name, bounded_spawn_poll_name, emit_expr,
    full_type_mono,
};
use crate::iface::*;
use crate::names::*;
use crate::stmt::{emit_block, emit_return_fallback};

pub fn emit_c(checked: &CheckedFile) -> String {
    emit_c_with(checked, EmitOptions::default())
}

/// Emit C with options (normal binary or test harness).
pub fn emit_c_with(checked: &CheckedFile, opts: EmitOptions) -> String {
    let mut out = String::new();
    out.push_str("/* generated by aura-codegen (C3 C backend) */\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <stdlib.h>\n");
    out.push_str("#include <stdio.h>\n");
    out.push_str("#include <string.h>\n");
    out.push_str("#include <errno.h>\n");
    out.push_str("#include <setjmp.h>\n");
    emit_ffi_abi_declarations(&mut out);
    emit_foreign_prototypes(&mut out, checked);
    out.push_str("void aura_print(const char *s);\n");
    out.push_str("void aura_println(const char *s);\n");
    out.push_str("void aura_eprint(const char *s);\n");
    out.push_str("void aura_eprintln(const char *s);\n");
    out.push_str("const char *aura_read_file(const char *path);\n");
    out.push_str("const char *aura_try_read_file(const char *path);\n");
    out.push_str("void aura_write_file(const char *path, const char *content);\n");
    out.push_str("_Bool aura_try_write_file(const char *path, const char *content);\n");
    out.push_str("void aura_append_file(const char *path, const char *content);\n");
    out.push_str("_Bool aura_file_exists(const char *path);\n");
    out.push_str("int64_t aura_file_size(const char *path);\n");
    out.push_str("int64_t aura_args_count(void);\n");
    out.push_str("const char *aura_args_get(int64_t i);\n");
    out.push_str("const char *aura_read_line(void);\n");
    out.push_str("const char *aura_read_all_stdin(void);\n");
    out.push_str("void aura_exit(int64_t code);\n");
    out.push_str("void aura_assert(_Bool cond);\n");
    out.push_str("void aura_assert_eq_int(int64_t a, int64_t b);\n");
    out.push_str("void aura_assert_eq_string(const char *a, const char *b);\n");
    out.push_str("void aura_assert_eq_bool(_Bool a, _Bool b);\n");
    out.push_str("void aura_try_enter(jmp_buf *buf);\n");
    out.push_str("void aura_try_leave(void);\n");
    out.push_str("void aura_throw_string(const char *s);\n");
    out.push_str("void aura_throw_int(int64_t v);\n");
    out.push_str("void aura_throw_bool(_Bool v);\n");
    out.push_str("void aura_throw_obj(const char *type_name, void *obj);\n");
    out.push_str("int aura_ex_matches(const char *type_name);\n");
    out.push_str("const char *aura_ex_as_string(void);\n");
    out.push_str("int64_t aura_ex_as_int(void);\n");
    out.push_str("_Bool aura_ex_as_bool(void);\n");
    out.push_str("void *aura_ex_as_obj(void);\n");
    out.push_str("void aura_ex_clear(void);\n");
    out.push_str("void aura_ex_rethrow(void);\n");
    out.push_str("void *aura_gc_alloc(size_t size);\n");
    out.push_str(
        "void *aura_gc_alloc_full(size_t size, void (*dtor)(void *), void (*mark_extras)(void *));\n",
    );
    out.push_str("void aura_gc_mark_ptr(void *obj);\n");
    out.push_str("void aura_gc_add_root(void **slot);\n");
    out.push_str("void aura_gc_remove_root(void **slot);\n");
    out.push_str("void aura_gc_add_array_root(void **data_slot, int64_t *len_slot);\n");
    out.push_str("void aura_gc_remove_array_root(void **data_slot);\n");
    out.push_str("void aura_fun_env_retain(void *env);\n");
    out.push_str("void aura_fun_env_free(void *env);\n");
    out.push_str("void aura_gc_collect(void);\n");
    out.push_str("void aura_gc_shutdown(void);\n");
    out.push_str("uint32_t aura_runtime_abi_version(void);\n");
    out.push_str(
        "int aura_runtime_check_abi(uint32_t expected_version, const char *expected_identity);\n",
    );
    out.push_str("const char *aura_runtime_abi_identity(void);\n");
    let abi_id = crate::runtime_abi::ID
        .replace('\\', "\\\\")
        .replace('"', "\\\"");
    let _ = writeln!(
        out,
        "#define AURA_GENERATED_ABI_VERSION {}u",
        crate::runtime_abi::VERSION
    );
    let _ = writeln!(out, "#define AURA_GENERATED_ABI_ID \"{abi_id}\"");
    // C22 runtime ABI.  The definitions live in runtime/aura_rt.c; generated
    // translation units only need the stable opaque declarations below.
    out.push_str("typedef struct AuraTaskFrame AuraTaskFrame;\n");
    out.push_str("typedef struct AuraTaskExecutor AuraTaskExecutor;\n");
    out.push_str("typedef struct AuraTaskChannel AuraTaskChannel;\n");
    out.push_str("typedef struct AuraRaceTracker AuraRaceTracker;\n");
    out.push_str("typedef enum { AURA_RACE_READ = 0, AURA_RACE_WRITE = 1, AURA_RACE_TASK_SPAWN = 2, AURA_RACE_TASK_JOIN = 3, AURA_RACE_SYNC_ACQUIRE = 4, AURA_RACE_SYNC_RELEASE = 5, AURA_RACE_TASK_COMPLETE = 6, AURA_RACE_TASK_FAILED = 7, AURA_RACE_TASK_CANCELLED = 8, AURA_RACE_CHANNEL_SEND = 9, AURA_RACE_CHANNEL_RECEIVE = 10, AURA_RACE_CHANNEL_CLOSE = 11 } AuraRaceEventKind;\n");
    out.push_str("AuraRaceTracker *aura_race_tracker_new(void);\n");
    out.push_str("void aura_race_tracker_destroy(AuraRaceTracker *tracker);\n");
    out.push_str("void aura_race_tracker_set_active(AuraRaceTracker *tracker);\n");
    out.push_str("void aura_race_set_source_id(uint32_t source_id);\n");
    out.push_str("void aura_race_record_access(uintptr_t address, uint32_t source_id, AuraRaceEventKind kind);\n");
    out.push_str("typedef void (*AuraTaskChannelValueDestroyFn)(void *data, size_t size);\n");
    out.push_str("typedef struct { void *data; size_t size; AuraTaskChannelValueDestroyFn destroy; } AuraTaskChannelValue;\n");
    out.push_str("typedef enum { AURA_CHANNEL_OK = 0, AURA_CHANNEL_PENDING = 1, AURA_CHANNEL_CLOSED = 2, AURA_CHANNEL_ERROR = 3 } AuraTaskChannelStatus;\n");
    out.push_str("typedef enum { AURA_TASK_READY = 0, AURA_TASK_PENDING = 1, AURA_TASK_COMPLETE = 2, AURA_TASK_FAILED = 3, AURA_TASK_CANCELLED = 4 } AuraTaskPollState;\n");
    out.push_str("typedef struct { void *data; size_t size; } AuraTaskResult;\n");
    out.push_str("typedef AuraTaskPollState (*AuraTaskPollFn)(AuraTaskFrame *frame);\n");
    out.push_str("typedef void (*AuraTaskFrameDestroyFn)(AuraTaskFrame *frame);\n");
    out.push_str("typedef void (*AuraTaskResultDestroyFn)(void *data, size_t size);\n");
    out.push_str("AuraTaskPollState aura_task_poll_unit(AuraTaskFrame *frame);\n");
    out.push_str("AuraTaskFrame *aura_task_frame_new(size_t data_size, AuraTaskPollFn poll, AuraTaskFrameDestroyFn destroy);\n");
    out.push_str("void *aura_task_frame_data(AuraTaskFrame *frame);\n");
    out.push_str("uint64_t aura_task_frame_task_id(const AuraTaskFrame *frame);\n");
    out.push_str(
        "void aura_task_frame_set_race_source_id(AuraTaskFrame *frame, uint32_t source_id);\n",
    );
    out.push_str("uint32_t aura_task_frame_error_source_id(const AuraTaskFrame *frame);\n");
    out.push_str("void aura_task_frame_set_error_at(AuraTaskFrame *frame, void *data, size_t size, AuraTaskResultDestroyFn destroy, uint32_t source_id);\n");
    out.push_str("AuraTaskPollState aura_task_frame_poll_once(AuraTaskFrame *frame);\n");
    out.push_str("void aura_task_frame_destroy(AuraTaskFrame *frame);\n");
    out.push_str("AuraTaskPollState aura_task_frame_state(const AuraTaskFrame *frame);\n");
    out.push_str("int aura_task_frame_cancel_requested(const AuraTaskFrame *frame);\n");
    out.push_str("int aura_task_frame_is_waiting(const AuraTaskFrame *frame);\n");
    out.push_str("uint32_t aura_task_frame_resume_state(const AuraTaskFrame *frame);\n");
    out.push_str("void aura_task_frame_set_resume_state(AuraTaskFrame *frame, uint32_t state);\n");
    out.push_str("void aura_task_frame_set_result(AuraTaskFrame *frame, void *data, size_t size, AuraTaskResultDestroyFn destroy);\n");
    out.push_str("AuraTaskResult aura_task_frame_result(const AuraTaskFrame *frame);\n");
    out.push_str("AuraTaskExecutor *aura_task_executor_new(void);\n");
    out.push_str("void aura_task_executor_set_race_tracker(AuraTaskExecutor *executor, AuraRaceTracker *tracker);\n");
    out.push_str(
        "int aura_task_executor_submit(AuraTaskExecutor *executor, AuraTaskFrame *frame);\n",
    );
    out.push_str(
        "int aura_task_executor_wake(AuraTaskExecutor *executor, AuraTaskFrame *frame);\n",
    );
    out.push_str(
        "int aura_task_executor_cancel(AuraTaskExecutor *executor, AuraTaskFrame *frame);\n",
    );
    out.push_str(
        "AuraTaskPollState aura_task_executor_join(AuraTaskExecutor *executor, AuraTaskFrame *frame, AuraTaskResult *out_result, AuraTaskResult *out_error);\n",
    );
    out.push_str(
        "int aura_task_executor_release(AuraTaskExecutor *executor, AuraTaskFrame **handle);\n",
    );
    out.push_str("int aura_task_executor_run_one(AuraTaskExecutor *executor);\n");
    out.push_str("size_t aura_task_executor_run(AuraTaskExecutor *executor);\n");
    out.push_str("void aura_task_executor_shutdown(AuraTaskExecutor *executor);\n");
    out.push_str("static AuraTaskExecutor *__aura_task_executor = NULL;\n");
    out.push_str("static AuraRaceTracker *__aura_race_tracker = NULL;\n");
    out.push_str("AuraTaskChannel *aura_task_channel_new(size_t capacity);\n");
    out.push_str("AuraTaskChannelStatus aura_task_channel_send(AuraTaskChannel *channel, AuraTaskFrame *sender, AuraTaskChannelValue value);\n");
    out.push_str("AuraTaskChannelStatus aura_task_channel_receive(AuraTaskChannel *channel, AuraTaskFrame *receiver, AuraTaskChannelValue *out);\n");
    out.push_str("int aura_task_channel_close(AuraTaskChannel *channel);\n");
    out.push_str("void aura_task_channel_destroy(AuraTaskChannel *channel);\n");
    out.push_str("void aura_task_channel_value_destroy_free(void *data, size_t size);\n");
    out.push_str("void aura_task_channel_value_destroy_class(void *data, size_t size);\n");
    // C12m/C13f: shared mutable boxes for var Int/Bool/String captures.
    out.push_str("typedef struct aura_box_i64 { int64_t value; int32_t refs; } aura_box_i64;\n");
    out.push_str("typedef struct aura_box_bool { _Bool value; int32_t refs; } aura_box_bool;\n");
    out.push_str(
        "typedef struct aura_box_str { const char *value; int32_t refs; } aura_box_str;\n",
    );
    out.push_str("aura_box_i64 *aura_box_i64_new(int64_t v);\n");
    out.push_str("void aura_box_i64_retain(aura_box_i64 *b);\n");
    out.push_str("void aura_box_i64_release(aura_box_i64 *b);\n");
    out.push_str("aura_box_bool *aura_box_bool_new(_Bool v);\n");
    out.push_str("void aura_box_bool_retain(aura_box_bool *b);\n");
    out.push_str("void aura_box_bool_release(aura_box_bool *b);\n");
    out.push_str("aura_box_str *aura_box_str_new(const char *v);\n");
    out.push_str("void aura_box_str_retain(aura_box_str *b);\n");
    out.push_str("void aura_box_str_release(aura_box_str *b);\n");
    out.push_str("const char *aura_box_str_set(aura_box_str *b, const char *v);\n");
    out.push_str("const char *aura_box_str_get(aura_box_str *b);\n");
    out.push_str("typedef void (*aura_box_ptr_drop_fn)(void *value);\n");
    out.push_str("typedef struct aura_box_ptr { void *value; int32_t refs; aura_box_ptr_drop_fn drop; } aura_box_ptr;\n");
    out.push_str("aura_box_ptr *aura_box_ptr_new(void *value, aura_box_ptr_drop_fn drop);\n");
    out.push_str("void aura_box_ptr_retain(aura_box_ptr *b);\n");
    out.push_str("void aura_box_ptr_release(aura_box_ptr *b);\n");
    out.push_str("void *aura_box_ptr_get(const aura_box_ptr *b);\n");
    out.push_str(
        "void *aura_box_ptr_set(aura_box_ptr *b, void *value, aura_box_ptr_drop_fn drop);\n",
    );
    out.push_str("int aura_main(void);\n\n");
    // C7a: tagged optional primitives (Int? / Bool?).
    out.push_str("typedef struct { _Bool has; int64_t value; } aura_opt_i64;\n");
    out.push_str("typedef struct { _Bool has; _Bool value; } aura_opt_bool;\n");
    // C13c: Int.toString — malloc'd decimal; caller owns (like other owned strings).
    out.push_str("const char *aura_i64_to_string(int64_t v);\n\n");
    out.push_str("int64_t aura_hash_string(const char *s);\n\n");

    // Stable class tags for interface dispatch (C9a: include generic monomorphs).
    let mut tag_monos: Vec<String> = Vec::new();
    for c in &checked.ast.classes {
        if c.kind != NominalKind::Class {
            continue;
        }
        if c.type_params.is_empty() {
            let pkg = class_decl_package(c, checked);
            tag_monos.push(type_mono(&pkg, &c.name.name, &[]));
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked
            .ast
            .classes
            .iter()
            .find(|c| c.name.name == *name && c.kind == NominalKind::Class)
        {
            let pkg = class_decl_package(c, checked);
            let mono = type_mono(&pkg, &c.name.name, args);
            if !tag_monos.contains(&mono) {
                tag_monos.push(mono);
            }
        }
    }
    if !tag_monos.is_empty() {
        out.push_str("enum {\n");
        for (i, mono) in tag_monos.iter().enumerate() {
            let _ = writeln!(out, "  AURA_TAG_{mono} = {i},");
        }
        out.push_str("  AURA_TAG__COUNT\n};\n\n");
    }

    // Class typedefs — non-generic classes + monomorphized generic classes.
    // C4u: incomplete struct forwards so nested monomorph field pointers compile
    // regardless of alphabetical mono_classes order (Outer_String → Wrapper_String).
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            let pkg = class_decl_package(c, checked);
            let mono = type_mono(&pkg, &c.name.name, &[]);
            let _ = writeln!(
                out,
                "typedef struct {} {};",
                c_class_type(&mono),
                c_class_type(&mono)
            );
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            let pkg = class_decl_package(c, checked);
            let mono = type_mono(&pkg, &c.name.name, args);
            let _ = writeln!(
                out,
                "typedef struct {} {};",
                c_class_type(&mono),
                c_class_type(&mono)
            );
        }
    }
    // C6g: enums + value structs must be complete before Array monomorphs
    // (Array stores them by value / sizeof). Heap classes stay incomplete here
    // so Array-of-class can use pointers only.
    for e in &checked.ast.enums {
        if e.type_params.is_empty() {
            emit_enum_typedef(&mut out, checked, e, &[]);
        }
    }
    for (name, args) in &checked.mono_enums {
        if let Some(e) = checked.ast.enums.iter().find(|e| e.name.name == *name) {
            emit_enum_typedef(&mut out, checked, e, args);
        }
    }
    for c in &checked.ast.classes {
        if c.type_params.is_empty() && c.kind == NominalKind::Struct {
            emit_class_typedef(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked
            .ast
            .classes
            .iter()
            .find(|c| c.name.name == *name && c.kind == NominalKind::Struct)
        {
            emit_class_typedef(&mut out, checked, c, args);
        }
    }

    // C6f/C8e: Array monomorphs before heap class bodies so classes may embed Array by value.
    // Nesting order: emit leaf Array_Int before Array_Array_Int (by mono_suffix depth).
    let mut array_monos: Vec<&[Ty]> = checked
        .mono_classes
        .iter()
        .filter(|(name, _)| is_array_mono(name))
        .map(|(_, args)| args.as_slice())
        .collect();
    array_monos.sort_by_key(|args| {
        // Fewer nested Array_ prefixes first (rough: shorter mono key first among Array_*).
        args.first()
            .map(|e| e.mono_suffix().matches("Array_").count())
            .unwrap_or(0)
    });
    for args in array_monos {
        if let Some(elem) = args.first() {
            emit_array_mono(&mut out, elem, checked);
        }
    }
    for c in &checked.ast.classes {
        if c.type_params.is_empty() && c.kind == NominalKind::Class {
            emit_class_typedef(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked
            .ast
            .classes
            .iter()
            .find(|c| c.name.name == *name && c.kind == NominalKind::Class)
        {
            emit_class_typedef(&mut out, checked, c, args);
        }
    }

    // Interface tagged unions (C4d/C8c/C9a: mono class implementors)
    let mut emit_iface_union = |iface: &InterfaceDecl, args: &[Ty]| {
        let imono = iface_mono_args(iface, checked, args);
        let impls = crate::iface::mono_implementors_for_iface(checked, iface, args);
        let _ = writeln!(out, "typedef struct {} {{", c_iface_type(&imono));
        out.push_str("  int tag;\n  union {\n");
        for imp in &impls {
            let pkg = class_decl_package(imp.class, checked);
            let mono = type_mono(&pkg, &imp.class.name.name, &imp.class_args);
            // C3y: heap classes stored as pointers inside the interface union.
            let field_ty = if is_heap_class_decl(imp.class) {
                format!("{} *", c_class_type(&mono))
            } else {
                c_class_type(&mono)
            };
            let _ = writeln!(out, "    {field_ty} as_{mono};");
        }
        if impls.is_empty() {
            out.push_str("    char _empty;\n");
        }
        let _ = writeln!(out, "  }} data;\n}} {};\n", c_iface_type(&imono));
    };
    for iface in &checked.ast.interfaces {
        if iface.type_params.is_empty() {
            emit_iface_union(iface, &[]);
        }
    }
    for (name, args) in &checked.mono_interfaces {
        if let Some(iface) = checked.ast.interfaces.iter().find(|i| i.name.name == *name) {
            emit_iface_union(iface, args);
        }
    }

    // Forward decls
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_forwards(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue; // Array defs already fully emitted
        }
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_forwards(&mut out, checked, c, args);
        }
    }
    for e in &checked.ast.enums {
        if e.type_params.is_empty() {
            emit_enum_forwards(&mut out, checked, e, &[]);
        }
    }
    for (name, args) in &checked.mono_enums {
        if let Some(e) = checked.ast.enums.iter().find(|e| e.name.name == *name) {
            emit_enum_forwards(&mut out, checked, e, args);
        }
    }
    for iface in &checked.ast.interfaces {
        if iface.type_params.is_empty() {
            let imono = iface_mono(iface, checked);
            for m in &iface.methods {
                let _ = writeln!(out, "{};", c_iface_method_signature(&imono, m, checked));
            }
        }
    }
    for (name, args) in &checked.mono_interfaces {
        if let Some(iface) = checked.ast.interfaces.iter().find(|i| i.name.name == *name) {
            let imono = iface_mono_args(iface, checked, args);
            let tparams: Vec<String> = iface
                .type_params
                .iter()
                .map(|p| p.name.name.clone())
                .collect();
            for m in &iface.methods {
                let _ = writeln!(
                    out,
                    "{};",
                    c_iface_method_signature_args(&imono, m, checked, &tparams, args)
                );
            }
        }
    }
    // C10e/f: fun-type typedefs must precede any signature using them.
    emit_fun_typedefs(&mut out, checked);

    for f in &checked.ast.functions {
        if f.name.name == "main" {
            continue;
        }
        if f.type_params.is_empty() {
            let _ = writeln!(out, "{};", c_fun_signature(f, checked, &[]));
        }
    }
    for (name, args) in &checked.mono_funs {
        if let Some(f) = checked.ast.functions.iter().find(|f| f.name.name == *name) {
            let _ = writeln!(out, "{};", c_fun_signature(f, checked, args));
        }
    }
    for f in &checked.ast.async_functions {
        if f.type_params.is_empty() {
            let _ = writeln!(out, "{};", c_async_fun_signature(f, checked));
        }
    }
    out.push('\n');

    // C22l: emit the bounded, capture-free spawn pollers after all ordinary
    // declarations are visible. Unsupported bodies keep the explicit abort
    // path in expression emission.
    emit_bounded_spawn_pollers(&mut out, checked, opts.detector);

    // Definitions
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_defs(&mut out, checked, c, &[], opts.detector);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_defs(&mut out, checked, c, args, opts.detector);
        }
    }

    for e in &checked.ast.enums {
        if e.type_params.is_empty() {
            emit_enum_defs(&mut out, checked, e, &[]);
        }
    }
    for (name, args) in &checked.mono_enums {
        if let Some(e) = checked.ast.enums.iter().find(|e| e.name.name == *name) {
            emit_enum_defs(&mut out, checked, e, args);
        }
    }

    for iface in &checked.ast.interfaces {
        if iface.type_params.is_empty() {
            for m in &iface.methods {
                emit_iface_dispatch(&mut out, checked, iface, m, &[]);
                out.push('\n');
            }
        }
    }
    for (name, args) in &checked.mono_interfaces {
        if let Some(iface) = checked.ast.interfaces.iter().find(|i| i.name.name == *name) {
            for m in &iface.methods {
                emit_iface_dispatch(&mut out, checked, iface, m, args);
                out.push('\n');
            }
        }
    }

    // C10e: non-capturing lambdas as static C functions (typedefs already emitted).
    emit_lambda_fns(&mut out, checked, opts.detector);

    for f in &checked.ast.functions {
        if f.type_params.is_empty() {
            emit_fun(&mut out, f, checked, &[], opts.detector);
            out.push('\n');
        }
    }
    for (name, args) in &checked.mono_funs {
        if let Some(f) = checked.ast.functions.iter().find(|f| f.name.name == *name) {
            emit_fun(&mut out, f, checked, args, opts.detector);
            out.push('\n');
        }
    }

    for f in &checked.ast.async_functions {
        if f.type_params.is_empty() {
            emit_async_fun_no_await(&mut out, f, checked, opts.detector);
            out.push('\n');
        }
    }

    if opts.test {
        emit_test_main(&mut out, checked, opts.detector);
    } else {
        out.push_str("int aura_main(void) {\n");
        out.push_str("  if (!aura_runtime_check_abi(AURA_GENERATED_ABI_VERSION, AURA_GENERATED_ABI_ID)) return 78;\n");
        out.push_str("  __aura_task_executor = aura_task_executor_new();\n");
        if opts.detector {
            out.push_str("  __aura_race_tracker = aura_race_tracker_new();\n");
            out.push_str("  aura_race_tracker_set_active(__aura_race_tracker);\n");
            out.push_str("  aura_task_executor_set_race_tracker(__aura_task_executor, __aura_race_tracker);\n");
        }
        if checked.ast.functions.iter().any(|f| f.name.name == "main") {
            out.push_str("  aura_fn_main();\n");
        }
        out.push_str("  aura_task_executor_shutdown(__aura_task_executor);\n");
        if opts.detector {
            out.push_str("  aura_race_tracker_destroy(__aura_race_tracker);\n");
        }
        out.push_str("  return 0;\n}\n");
    }
    out
}

/// F3: expose the stable allocation-only structured-value ABI to generated C.
/// Keep this self-contained because installed builds compile generated source
/// beside `aura_rt.c` without requiring a system include path.
fn emit_ffi_abi_declarations(out: &mut String) {
    out.push_str("#define AURA_FFI_ABI_VERSION 1u\n");
    out.push_str(
        "typedef enum { AURA_FFI_OK = 0, AURA_FFI_INVALID = 1, AURA_FFI_OOM = 2 } AuraFfiStatus;\n",
    );
    out.push_str("typedef struct { const char *data; uint64_t len; } AuraFfiStringView;\n");
    out.push_str("typedef struct { char *data; uint64_t len; } AuraFfiString;\n");
    out.push_str("typedef enum { AURA_FFI_ARRAY_BYTES = 1, AURA_FFI_ARRAY_INT64 = 2, AURA_FFI_ARRAY_BOOL = 3 } AuraFfiArrayKind;\n");
    out.push_str("typedef struct { const void *data; uint64_t len; uint64_t cap; uint64_t elem_size; AuraFfiArrayKind kind; } AuraFfiArrayView;\n");
    out.push_str("typedef struct { void *data; uint64_t len; uint64_t cap; uint64_t elem_size; AuraFfiArrayKind kind; } AuraFfiArray;\n");
    out.push_str("typedef struct { void **slot; int active; } AuraFfiRootGuard;\n");
    out.push_str(
        "AuraFfiStatus aura_ffi_string_borrow(const char *, uint64_t, AuraFfiStringView *);\n",
    );
    out.push_str("AuraFfiStatus aura_ffi_string_copy(AuraFfiStringView, AuraFfiString *);\n");
    out.push_str("AuraFfiStatus aura_ffi_string_transfer(char *, uint64_t, AuraFfiString *);\n");
    out.push_str("void aura_ffi_string_destroy(AuraFfiString *);\n");
    out.push_str("AuraFfiStatus aura_ffi_array_borrow(const void *, uint64_t, uint64_t, uint64_t, AuraFfiArrayKind, AuraFfiArrayView *);\n");
    out.push_str("AuraFfiStatus aura_ffi_array_copy(AuraFfiArrayView, AuraFfiArray *);\n");
    out.push_str("AuraFfiStatus aura_ffi_array_transfer(void *, uint64_t, uint64_t, uint64_t, AuraFfiArrayKind, AuraFfiArray *);\n");
    out.push_str("void aura_ffi_array_destroy(AuraFfiArray *);\n");
    out.push_str("AuraFfiStatus aura_ffi_root_begin(AuraFfiRootGuard *, void **);\n");
    out.push_str("void aura_ffi_root_end(AuraFfiRootGuard *);\n\n");
    out.push_str("typedef enum { AURA_FFI_OUTCOME_OK = 0, AURA_FFI_OUTCOME_CANCELLED = 1, AURA_FFI_OUTCOME_INVALID = 2, AURA_FFI_OUTCOME_NOT_FOUND = 3, AURA_FFI_OUTCOME_PERMISSION = 4, AURA_FFI_OUTCOME_UNAVAILABLE = 5, AURA_FFI_OUTCOME_TIMEOUT = 6, AURA_FFI_OUTCOME_FOREIGN_ERROR = 7 } AuraFfiOutcome;\n");
    out.push_str("AuraFfiOutcome aura_ffi_map_error(int32_t);\n\n");
}

/// F2: emit only the primitive C ABI surface declared by `@foreign`.
/// String is intentionally represented as a borrowed `const char *` handle.
fn emit_foreign_prototypes(out: &mut String, checked: &CheckedFile) {
    for foreign in &checked.ast.foreign_functions {
        let ret = crate::names::c_type_from_opt(&foreign.return_type, checked, &[], &[]);
        let params = foreign
            .params
            .iter()
            .map(|param| crate::names::c_type_ref_subst(&param.ty, checked, &[], &[]))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "extern {ret} {}({params});", foreign.name.name);
    }
    if !checked.ast.foreign_functions.is_empty() {
        out.push('\n');
    }
}

#[cfg(test)]
#[allow(clippy::items_after_test_module)]
mod abi_tests {
    use super::emit_c_with;
    use crate::ctx::EmitOptions;
    use aura_ast::{
        Attribute, AttributeArg, AttributeValue, Block, File, FunDecl, Ident, Path, Span,
    };
    use aura_parser::parse_file;

    #[test]
    fn generated_artifact_embeds_runtime_abi_identity_and_check() {
        let span = Span::new(0, 0);
        let file = File {
            package: Path {
                segments: vec![Ident {
                    name: "demo".into(),
                    span,
                }],
                span,
            },
            imports: vec![],
            interfaces: vec![],
            enums: vec![],
            classes: vec![],
            type_aliases: vec![],
            consts: vec![],
            functions: vec![],
            foreign_functions: vec![],
            async_functions: vec![],
            span,
        };
        let checked = aura_sema::check_file(&file).expect("empty file checks");
        let generated = emit_c_with(&checked, EmitOptions::default());
        assert!(generated.contains("#define AURA_GENERATED_ABI_ID \"aura-c-abi/1.0;"));
        assert!(generated.contains("#define AURA_GENERATED_ABI_VERSION 1u"));
        assert!(generated
            .contains("aura_runtime_check_abi(AURA_GENERATED_ABI_VERSION, AURA_GENERATED_ABI_ID)"));
    }
    #[test]
    fn checked_file_retains_attribute_metadata_for_consumers() {
        let span = Span::new(0, 1);
        let ident = |name: &str| Ident {
            name: name.into(),
            span,
        };
        let file = File {
            package: Path {
                segments: vec![ident("demo")],
                span,
            },
            imports: vec![],
            interfaces: vec![],
            enums: vec![],
            classes: vec![],
            type_aliases: vec![],
            consts: vec![],
            functions: vec![FunDecl {
                is_pub: false,
                origin_package: "demo".into(),
                attributes: vec![Attribute {
                    name: ident("deprecated"),
                    args: vec![AttributeArg::Positional(AttributeValue::String {
                        value: "use newer".into(),
                        span,
                    })],
                    span,
                }],
                is_test: false,
                name: ident("main"),
                type_params: vec![],
                params: vec![],
                return_type: None,
                body: Block {
                    stmts: vec![],
                    span,
                },
                span,
            }],
            foreign_functions: vec![],
            async_functions: vec![],
            span,
        };
        let checked = aura_sema::check_file(&file).expect("check attribute");
        let attribute = &checked.ast.functions[0].attributes[0];
        assert_eq!(attribute.name.name, "deprecated");
        assert_eq!(attribute.args.len(), 1);
    }

    #[test]
    fn hash_code_derive_reaches_c_codegen_with_builtin_hash_calls() {
        let file = parse_file(
            "package demo\n@derive(HashCode) class Key(val id: Int, val name: String) {}\n",
        )
        .expect("parse derive input");
        let checked = aura_sema::check_file(&file).expect("hashCode derive should typecheck");
        let generated = emit_c_with(&checked, EmitOptions::default());
        assert!(generated.contains("hashCode"));
        assert!(generated.contains("aura_hash_string("));
        assert!(generated.contains("INT64_C(31)"));
    }

    #[test]
    fn debug_derive_reaches_c_codegen_with_deterministic_string_parts() {
        let file = parse_file(
            "package demo\n@derive(Debug) class Point(val x: Int, val label: String) {}\n",
        )
        .expect("parse derive input");
        let checked = aura_sema::check_file(&file).expect("Debug derive should typecheck");
        let generated = emit_c_with(&checked, EmitOptions::default());
        assert!(generated.contains("toString"));
        assert!(generated.contains("aura_i64_to_string"));
        assert!(generated.contains("x="));
        assert!(generated.contains("label="));
    }

    #[test]
    fn detector_profile_instruments_reads_and_writes_with_source_ids() {
        let file = parse_file(
            "package demo\nfun main() {\n  var counter = 0\n  counter = counter + 1\n  println(counter.toString())\n}\n",
        )
        .expect("instrumentation fixture parses");
        let checked = aura_sema::check_file(&file).expect("instrumentation fixture checks");
        let plain = emit_c_with(&checked, EmitOptions::default());
        let instrumented = emit_c_with(
            &checked,
            EmitOptions {
                detector: true,
                ..Default::default()
            },
        );
        assert!(!plain.contains("aura_race_record_access((uintptr_t)&"));
        assert!(instrumented.contains("AURA_RACE_READ"));
        assert!(instrumented.contains("AURA_RACE_WRITE"));
        assert!(instrumented.contains("UINT32_C("));
    }
}

fn c_async_fun_signature(f: &AsyncFunDecl, checked: &CheckedFile) -> String {
    let params: Vec<String> = f.type_params.iter().map(|p| p.name.name.clone()).collect();
    let ps = if f.params.is_empty() {
        "void".into()
    } else {
        f.params
            .iter()
            .map(|p| {
                format!(
                    "{} {}",
                    c_type_ref_subst(&p.ty, checked, &params, &[]),
                    mangle_ident(&p.name.name)
                )
            })
            .collect::<Vec<_>>()
            .join(", ")
    };
    let pkg = async_fun_decl_package(f, checked);
    format!(
        "AuraTaskFrame * {}({ps})",
        c_fun_name(&pkg, &f.name.name, &[])
    )
}

/// C22l slice 1: lower an async function with no suspension points to a task
/// frame whose first poll executes an ordinary helper body exactly once.
fn emit_async_fun_no_await(
    out: &mut String,
    f: &AsyncFunDecl,
    checked: &CheckedFile,
    detector: bool,
) {
    let params: Vec<String> = f.type_params.iter().map(|p| p.name.name.clone()).collect();
    let pkg = async_fun_decl_package(f, checked);
    let base = format!("{}_{}", mangle_package(&pkg), mangle_ident(&f.name.name));
    let data_ty = format!("aura_async_data_{base}");
    let body_fn = format!("aura_async_body_{base}");
    let poll_fn = format!("aura_async_poll_{base}");
    let destroy_result = format!("aura_async_result_destroy_{base}");
    let ret = c_type_from_opt(&f.return_type, checked, &params, &[]);

    for point in f.suspension_points() {
        let kind = match point.kind {
            AsyncSuspensionKind::Await => "await",
        };
        let _ = writeln!(
            out,
            "/* aura async suspension state={} kind={} span={}:{} */",
            point.state_id, kind, point.span.start, point.span.end
        );
    }

    let _ = writeln!(out, "typedef struct {data_ty} {{");
    for p in &f.params {
        let _ = writeln!(
            out,
            "  {} {};",
            c_type_ref_subst(&p.ty, checked, &params, &[]),
            mangle_ident(&p.name.name)
        );
    }
    let _ = writeln!(out, "}} {data_ty};\n");

    let body_params = f
        .params
        .iter()
        .map(|p| {
            format!(
                "{} {}",
                c_type_ref_subst(&p.ty, checked, &params, &[]),
                mangle_ident(&p.name.name)
            )
        })
        .collect::<Vec<_>>();
    let _ = writeln!(
        out,
        "static {ret} {body_fn}({}) {{",
        if body_params.is_empty() {
            "void".into()
        } else {
            body_params.join(", ")
        }
    );
    emit_async_body(out, f, checked, &params, detector);
    out.push_str("}\n\n");

    let _ = writeln!(
        out,
        "static void {destroy_result}(void *data, size_t size) {{"
    );
    out.push_str("  (void)size;\n  free(data);\n}\n\n");
    let _ = writeln!(
        out,
        "static AuraTaskPollState {poll_fn}(AuraTaskFrame *frame) {{"
    );
    let _ = writeln!(
        out,
        "  {data_ty} *data = ({data_ty} *)aura_task_frame_data(frame);"
    );
    out.push_str("  if (aura_task_frame_cancel_requested(frame)) return AURA_TASK_CANCELLED;\n");
    out.push_str("  switch (aura_task_frame_resume_state(frame)) {\n");
    out.push_str("    case 0: break;\n");
    out.push_str("    case 1: return AURA_TASK_COMPLETE;\n");
    out.push_str("    default: return AURA_TASK_FAILED;\n");
    out.push_str("  }\n");
    out.push_str("  aura_task_frame_set_resume_state(frame, 1);\n");
    let args = f
        .params
        .iter()
        .map(|p| format!("data->{}", mangle_ident(&p.name.name)))
        .collect::<Vec<_>>()
        .join(", ");
    if ret == "void" {
        let _ = writeln!(out, "  {body_fn}({args});");
        out.push_str("  aura_task_frame_set_result(frame, NULL, 0, NULL);\n");
    } else {
        let _ = writeln!(out, "  {ret} *result = ({ret} *)malloc(sizeof(*result));");
        out.push_str("  if (result == NULL) return AURA_TASK_FAILED;\n");
        let _ = writeln!(out, "  *result = {body_fn}({args});");
        let _ = writeln!(
            out,
            "  aura_task_frame_set_result(frame, result, sizeof(*result), {destroy_result});"
        );
    }
    out.push_str("  return AURA_TASK_COMPLETE;\n}\n\n");

    let _ = writeln!(out, "{} {{", c_async_fun_signature(f, checked));
    let _ = writeln!(
        out,
        "  AuraTaskFrame *frame = aura_task_frame_new(sizeof({data_ty}), {poll_fn}, NULL);"
    );
    out.push_str("  if (frame == NULL) return NULL;\n");
    let _ = writeln!(
        out,
        "  {data_ty} *data = ({data_ty} *)aura_task_frame_data(frame);"
    );
    for p in &f.params {
        let n = mangle_ident(&p.name.name);
        let _ = writeln!(out, "  data->{n} = {n};");
    }
    out.push_str("  if (__aura_task_executor != NULL && !aura_task_executor_submit(__aura_task_executor, frame)) { aura_task_frame_destroy(frame); return NULL; }\n");
    out.push_str("  return frame;\n}\n");
}

fn emit_async_body(
    out: &mut String,
    f: &AsyncFunDecl,
    checked: &CheckedFile,
    params: &[String],
    detector: bool,
) {
    let ret_key = f
        .return_type
        .as_ref()
        .map(|t| type_ref_local_key_expand(t, params, &[], checked));
    let mut ctx = EmitCtx {
        checked,
        detector,
        method_class: None,
        type_params: params.to_vec(),
        type_args: Vec::new(),
        locals: vec![HashMap::new()],
        array_owners: vec![std::collections::HashSet::new()],
        fun_owners: vec![std::collections::HashSet::new()],
        string_owners: vec![std::collections::HashSet::new()],
        channel_owners: vec![std::collections::HashSet::new()],
        box_locals: vec![std::collections::HashSet::new()],
        box_owners: vec![std::collections::HashSet::new()],
        gc_roots: vec![std::collections::HashSet::new()],
        array_gc_roots: vec![std::collections::HashSet::new()],
        return_key: ret_key,
        lambda_ids: build_lambda_ids(checked),
        spawn_params: f.params.iter().map(|p| p.name.name.clone()).collect(),
    };
    for p in &f.params {
        let key = type_ref_local_key_expand(&p.ty, params, &[], checked);
        ctx.define_local(&p.name.name, full_type_mono(&key, checked));
    }
    emit_block(out, &f.body, 1, &mut ctx);
    crate::stmt::emit_free_fun_owners(out, 1, &ctx, &ctx.fun_owners_all());
    crate::stmt::emit_release_box_locals(out, 1, &ctx, &ctx.box_owners_all());
    emit_return_fallback(out, &f.return_type, checked, params, &[]);
}

pub(crate) fn emit_test_main(out: &mut String, checked: &CheckedFile, detector: bool) {
    let tests: Vec<_> = checked.ast.functions.iter().filter(|f| f.is_test).collect();
    out.push_str("int aura_main(void) {\n");
    out.push_str("  if (!aura_runtime_check_abi(AURA_GENERATED_ABI_VERSION, AURA_GENERATED_ABI_ID)) return 78;\n");
    out.push_str("  __aura_task_executor = aura_task_executor_new();\n");
    if detector {
        out.push_str("  __aura_race_tracker = aura_race_tracker_new();\n");
        out.push_str("  aura_race_tracker_set_active(__aura_race_tracker);\n");
        out.push_str(
            "  aura_task_executor_set_race_tracker(__aura_task_executor, __aura_race_tracker);\n",
        );
    }
    out.push_str("  int failed = 0;\n");
    out.push_str("  int ran = 0;\n");
    if tests.is_empty() {
        out.push_str("  puts(\"no tests\");\n");
        out.push_str("  aura_task_executor_shutdown(__aura_task_executor);\n");
        if detector {
            out.push_str("  aura_race_tracker_destroy(__aura_race_tracker);\n");
        }
        out.push_str("  return 0;\n}\n");
        return;
    }
    for t in &tests {
        let name = &t.name.name;
        let pkg = fun_decl_package(t, checked);
        let fn_c = c_fun_name(&pkg, name, &[]);
        let _ = writeln!(out, "  /* test {name} */");
        out.push_str("  {\n");
        out.push_str("    jmp_buf __tjb;\n");
        let _ = writeln!(out, "    printf(\"test {name} ... \");");
        out.push_str("    fflush(stdout);\n");
        out.push_str("    ran++;\n");
        out.push_str("    if (setjmp(__tjb) == 0) {\n");
        out.push_str("      aura_try_enter(&__tjb);\n");
        let _ = writeln!(out, "      {fn_c}();");
        out.push_str("      aura_try_leave();\n");
        out.push_str("      puts(\"ok\");\n");
        out.push_str("    } else {\n");
        out.push_str("      const char *__msg = aura_ex_matches(\"String\") ? aura_ex_as_string() : \"exception\";\n");
        out.push_str("      printf(\"FAILED (%s)\\n\", __msg ? __msg : \"?\");\n");
        out.push_str("      aura_ex_clear();\n");
        out.push_str("      aura_try_leave();\n");
        out.push_str("      failed++;\n");
        out.push_str("    }\n");
        out.push_str("  }\n");
    }
    out.push_str("  printf(\"%d passed, %d failed\\n\", ran - failed, failed);\n");
    out.push_str("  aura_task_executor_shutdown(__aura_task_executor);\n");
    if detector {
        out.push_str("  aura_race_tracker_destroy(__aura_race_tracker);\n");
    }
    out.push_str("  return failed ? 1 : 0;\n}\n");
}

/// C10e: map LambdaExpr.span.start → stable sequential id (sorted by span).
pub(crate) fn build_lambda_ids(checked: &CheckedFile) -> HashMap<u32, usize> {
    let mut starts: Vec<u32> = checked.lambda_tys.keys().copied().collect();
    starts.sort_unstable();
    starts
        .into_iter()
        .enumerate()
        .map(|(i, s)| (s, i))
        .collect()
}

fn emit_bounded_spawn_pollers(out: &mut String, checked: &CheckedFile, detector: bool) {
    let mut spawns = Vec::new();
    for f in &checked.ast.functions {
        let available = spawn_parameter_locals(&f.params, &[], &[], checked);
        collect_spawns_block(&f.body, &available, &mut spawns);
    }
    for f in &checked.ast.async_functions {
        let params: Vec<String> = f.type_params.iter().map(|p| p.name.name.clone()).collect();
        let available = spawn_parameter_locals(&f.params, &params, &[], checked);
        collect_spawns_block(&f.body, &available, &mut spawns);
    }
    for c in &checked.ast.classes {
        for m in &c.methods {
            collect_spawns_block(&m.body, &HashMap::new(), &mut spawns);
        }
    }
    for c in &checked.ast.consts {
        collect_spawns_expr(&c.value, &HashMap::new(), &mut spawns);
    }

    let mut emitted = std::collections::HashSet::new();
    for (spawn, available) in spawns {
        let Some(captures) = bounded_spawn_captures(&spawn.body, &available, checked) else {
            continue;
        };
        if spawn.body.stmts.is_empty() || !emitted.insert(spawn.span.start) {
            continue;
        }
        let poll = bounded_spawn_poll_name(spawn.span);
        let destroy = bounded_spawn_destroy_name(spawn.span);
        let data_ty = format!("aura_spawn_data_{}", spawn.span.start);
        if !captures.is_empty() {
            let _ = writeln!(out, "typedef struct {data_ty} {{");
            for (name, key) in &captures {
                let cty = if key == "String" {
                    "aura_box_str *".to_string()
                } else {
                    crate::stmt::local_key_to_c(key, checked)
                };
                let _ = writeln!(out, "  {} {};", cty, mangle_ident(name));
            }
            let _ = writeln!(out, "}} {data_ty};\n");
            let _ = writeln!(out, "static void {destroy}(AuraTaskFrame *frame) {{");
            let _ = writeln!(
                out,
                "  {data_ty} *data = ({data_ty} *)aura_task_frame_data(frame);"
            );
            for (name, key) in &captures {
                if key == "String" {
                    let n = mangle_ident(name);
                    let _ = writeln!(
                        out,
                        "  if (data != NULL && data->{n} != NULL) aura_box_str_release(data->{n});"
                    );
                } else if is_heap_class_mono(key, checked) {
                    let n = mangle_ident(name);
                    let _ = writeln!(
                        out,
                        "  if (data != NULL && data->{n} != NULL) aura_gc_remove_root((void **)&data->{n});"
                    );
                } else if is_array_type_key(key) {
                    crate::array_emit::emit_array_contents_free(
                        out,
                        2,
                        &format!("data->{}", mangle_ident(name)),
                        key,
                    );
                } else if is_fun_type_key(key) {
                    let n = mangle_ident(name);
                    let _ = writeln!(
                        out,
                        "  if (data != NULL && data->{n}.env != NULL) aura_fun_env_free(data->{n}.env);"
                    );
                }
            }
            out.push_str("}\n\n");
        }
        let _ = writeln!(
            out,
            "static AuraTaskPollState {poll}(AuraTaskFrame *frame) {{"
        );
        if !captures.is_empty() {
            let _ = writeln!(
                out,
                "  {data_ty} *data = ({data_ty} *)aura_task_frame_data(frame);"
            );
            for (name, key) in &captures {
                let n = mangle_ident(name);
                if key == "String" {
                    let _ = writeln!(
                        out,
                        "  const char *{n} = data->{n} != NULL ? data->{n}->value : NULL;"
                    );
                } else if is_array_type_key(key) {
                    let _ = writeln!(
                        out,
                        "  {} {n} = {}(&data->{n});",
                        crate::stmt::local_key_to_c(key, checked),
                        crate::names::c_method_name(key, "clone")
                    );
                } else if is_fun_type_key(key) {
                    let _ = writeln!(
                        out,
                        "  {} {n} = data->{n}; if ({n}.env != NULL) aura_fun_env_retain({n}.env);",
                        crate::stmt::local_key_to_c(key, checked)
                    );
                } else {
                    let _ = writeln!(
                        out,
                        "  {} {n} = data->{n};",
                        crate::stmt::local_key_to_c(key, checked)
                    );
                }
            }
        }
        out.push_str(
            "  if (aura_task_frame_cancel_requested(frame)) return AURA_TASK_CANCELLED;\n",
        );
        out.push_str(
            "  if (aura_task_frame_resume_state(frame) != 0) return AURA_TASK_COMPLETE;\n",
        );
        out.push_str("  aura_task_frame_set_resume_state(frame, 1);\n");
        let mut ctx = EmitCtx {
            checked,
            detector,
            method_class: None,
            type_params: Vec::new(),
            type_args: Vec::new(),
            locals: vec![HashMap::new()],
            array_owners: vec![std::collections::HashSet::new()],
            fun_owners: vec![std::collections::HashSet::new()],
            string_owners: vec![std::collections::HashSet::new()],
            channel_owners: vec![std::collections::HashSet::new()],
            box_locals: vec![std::collections::HashSet::new()],
            box_owners: vec![std::collections::HashSet::new()],
            gc_roots: vec![std::collections::HashSet::new()],
            array_gc_roots: vec![std::collections::HashSet::new()],
            return_key: Some("Unit".into()),
            lambda_ids: build_lambda_ids(checked),
            spawn_params: HashSet::new(),
        };
        for (name, key) in &captures {
            ctx.define_local(name, key.clone());
            if is_array_type_key(key) {
                ctx.mark_array_owner(name);
            }
            if is_fun_type_key(key) {
                ctx.mark_fun_owner(name);
            }
        }
        for stmt in &spawn.body.stmts {
            if let Stmt::Expr(expr) = stmt {
                let code = emit_expr(expr, &mut ctx);
                let _ = writeln!(out, "  {code};");
            }
        }
        let array_owners = ctx.array_owners_all();
        crate::stmt::emit_free_array_owners(out, 1, &ctx, &array_owners);
        let fun_owners = ctx.fun_owners_all();
        crate::stmt::emit_free_fun_owners(out, 1, &ctx, &fun_owners);
        out.push_str("  return AURA_TASK_COMPLETE;\n}\n\n");
    }
}

fn spawn_parameter_locals(
    params: &[Param],
    type_params: &[String],
    type_args: &[Ty],
    checked: &CheckedFile,
) -> HashMap<String, String> {
    params
        .iter()
        .map(|p| {
            let key = type_ref_local_key_expand(&p.ty, type_params, type_args, checked);
            (p.name.name.clone(), full_type_mono(&key, checked))
        })
        .collect()
}

fn collect_spawns_block<'a>(
    block: &'a Block,
    available: &HashMap<String, String>,
    out: &mut Vec<(&'a SpawnExpr, HashMap<String, String>)>,
) {
    for stmt in &block.stmts {
        match stmt {
            Stmt::Var(v) => collect_spawns_expr(&v.init, available, out),
            Stmt::If(i) => {
                collect_spawns_expr(&i.cond, available, out);
                collect_spawns_block(&i.then_block, available, out);
                if let Some(b) = &i.else_block {
                    collect_spawns_block(b, available, out);
                }
            }
            Stmt::While(w) => {
                collect_spawns_expr(&w.cond, available, out);
                collect_spawns_block(&w.body, available, out);
            }
            Stmt::ForRange(f) => {
                collect_spawns_expr(&f.start, available, out);
                collect_spawns_expr(&f.end, available, out);
                collect_spawns_block(&f.body, available, out);
            }
            Stmt::ForIn(f) => {
                collect_spawns_expr(&f.iterable, available, out);
                collect_spawns_block(&f.body, available, out);
            }
            Stmt::Match(m) => {
                collect_spawns_expr(&m.scrutinee, available, out);
                for arm in &m.arms {
                    collect_spawns_block(&arm.body, available, out);
                }
            }
            Stmt::Try(t) => {
                collect_spawns_block(&t.try_block, available, out);
                if let Some(c) = &t.catch {
                    collect_spawns_block(&c.body, available, out);
                }
                if let Some(f) = &t.finally {
                    collect_spawns_block(f, available, out);
                }
            }
            Stmt::Throw(t) => collect_spawns_expr(&t.value, available, out),
            Stmt::Return(r) => {
                if let Some(e) = &r.value {
                    collect_spawns_expr(e, available, out);
                }
            }
            Stmt::Expr(e) => collect_spawns_expr(e, available, out),
            Stmt::Break(_) | Stmt::Continue(_) => {}
        }
    }
}

fn collect_spawns_expr<'a>(
    expr: &'a Expr,
    available: &HashMap<String, String>,
    out: &mut Vec<(&'a SpawnExpr, HashMap<String, String>)>,
) {
    match expr {
        Expr::Call(c) => {
            collect_spawns_expr(&c.callee, available, out);
            for arg in &c.args {
                collect_spawns_expr(arg, available, out);
            }
        }
        Expr::Field(f) => collect_spawns_expr(&f.object, available, out),
        Expr::Assign(a) => collect_spawns_expr(&a.value, available, out),
        Expr::Binary(b) => {
            collect_spawns_expr(&b.left, available, out);
            collect_spawns_expr(&b.right, available, out);
        }
        Expr::Unary(u) => collect_spawns_expr(&u.expr, available, out),
        Expr::ForceUnwrap(f) => collect_spawns_expr(&f.expr, available, out),
        Expr::Is(i) => collect_spawns_expr(&i.expr, available, out),
        Expr::Group(e, _) => collect_spawns_expr(e, available, out),
        Expr::If(i) => {
            collect_spawns_expr(&i.cond, available, out);
            collect_spawns_block(&i.then_block, available, out);
            collect_spawns_block(&i.else_block, available, out);
        }
        Expr::Lambda(l) => match &l.body {
            LambdaBody::Expr(e) => collect_spawns_expr(e, available, out),
            LambdaBody::Block(b) => collect_spawns_block(b, available, out),
        },
        Expr::Async(a) => match a {
            AsyncExpr::Spawn(s) => {
                out.push((s, available.clone()));
                collect_spawns_block(&s.body, available, out);
            }
            AsyncExpr::Await(a) => collect_spawns_expr(&a.operand, available, out),
            AsyncExpr::Join(j) => collect_spawns_expr(&j.handle, available, out),
            AsyncExpr::Cancel(c) => collect_spawns_expr(&c.handle, available, out),
            AsyncExpr::ChannelCreate(c) => collect_spawns_expr(&c.capacity, available, out),
            AsyncExpr::ChannelSend(c) => {
                collect_spawns_expr(&c.channel, available, out);
                collect_spawns_expr(&c.value, available, out);
            }
            AsyncExpr::ChannelReceive(c) => collect_spawns_expr(&c.channel, available, out),
            AsyncExpr::ChannelClose(c) => collect_spawns_expr(&c.channel, available, out),
        },
        Expr::Ident(_)
        | Expr::This(_)
        | Expr::Int(_)
        | Expr::Bool(_)
        | Expr::String(_)
        | Expr::Null(_) => {}
    }
}

/// Collect LambdaExpr nodes from the AST (for body emission).
fn collect_lambdas(file: &File) -> Vec<&LambdaExpr> {
    let mut out = Vec::new();
    for f in &file.functions {
        walk_block_lambdas(&f.body, &mut out);
    }
    for c in &file.classes {
        for m in &c.methods {
            walk_block_lambdas(&m.body, &mut out);
        }
    }
    for k in &file.consts {
        walk_expr_lambdas(&k.value, &mut out);
    }
    out
}

fn walk_block_lambdas<'a>(b: &'a Block, out: &mut Vec<&'a LambdaExpr>) {
    for s in &b.stmts {
        walk_stmt_lambdas(s, out);
    }
}

fn walk_stmt_lambdas<'a>(s: &'a Stmt, out: &mut Vec<&'a LambdaExpr>) {
    match s {
        Stmt::Var(v) => walk_expr_lambdas(&v.init, out),
        Stmt::If(i) => {
            walk_expr_lambdas(&i.cond, out);
            walk_block_lambdas(&i.then_block, out);
            if let Some(e) = &i.else_block {
                walk_block_lambdas(e, out);
            }
        }
        Stmt::While(w) => {
            walk_expr_lambdas(&w.cond, out);
            walk_block_lambdas(&w.body, out);
        }
        Stmt::ForRange(f) => {
            walk_expr_lambdas(&f.start, out);
            walk_expr_lambdas(&f.end, out);
            walk_block_lambdas(&f.body, out);
        }
        Stmt::ForIn(f) => {
            walk_expr_lambdas(&f.iterable, out);
            walk_block_lambdas(&f.body, out);
        }
        Stmt::Match(m) => {
            walk_expr_lambdas(&m.scrutinee, out);
            for a in &m.arms {
                walk_block_lambdas(&a.body, out);
            }
        }
        Stmt::Try(t) => {
            walk_block_lambdas(&t.try_block, out);
            if let Some(c) = &t.catch {
                walk_block_lambdas(&c.body, out);
            }
            if let Some(f) = &t.finally {
                walk_block_lambdas(f, out);
            }
        }
        Stmt::Throw(t) => walk_expr_lambdas(&t.value, out),
        Stmt::Return(r) => {
            if let Some(e) = &r.value {
                walk_expr_lambdas(e, out);
            }
        }
        Stmt::Expr(e) => walk_expr_lambdas(e, out),
        Stmt::Break(_) | Stmt::Continue(_) => {}
    }
}

fn walk_expr_lambdas<'a>(e: &'a Expr, out: &mut Vec<&'a LambdaExpr>) {
    match e {
        Expr::Lambda(l) => {
            out.push(l);
            match &l.body {
                LambdaBody::Expr(body) => walk_expr_lambdas(body, out),
                LambdaBody::Block(block) => walk_block_lambdas(block, out),
            }
        }
        Expr::Call(c) => {
            walk_expr_lambdas(&c.callee, out);
            for a in &c.args {
                walk_expr_lambdas(a, out);
            }
        }
        Expr::Field(f) => walk_expr_lambdas(&f.object, out),
        Expr::Assign(a) => walk_expr_lambdas(&a.value, out),
        Expr::Binary(b) => {
            walk_expr_lambdas(&b.left, out);
            walk_expr_lambdas(&b.right, out);
        }
        Expr::Unary(u) => walk_expr_lambdas(&u.expr, out),
        Expr::ForceUnwrap(f) => walk_expr_lambdas(&f.expr, out),
        Expr::Is(i) => walk_expr_lambdas(&i.expr, out),
        Expr::Group(inner, _) => walk_expr_lambdas(inner, out),
        Expr::If(i) => {
            walk_expr_lambdas(&i.cond, out);
            walk_block_lambdas(&i.then_block, out);
            walk_block_lambdas(&i.else_block, out);
        }
        Expr::Async(_) => {}
        Expr::Ident(_)
        | Expr::This(_)
        | Expr::Int(_)
        | Expr::Bool(_)
        | Expr::String(_)
        | Expr::Null(_) => {}
    }
}

/// Collect Fun types that need C typedefs (lambdas + AST annotations).
fn collect_fun_tys(checked: &CheckedFile) -> Vec<Ty> {
    let mut out: Vec<Ty> = checked.lambda_tys.values().cloned().collect();
    fn from_type_ref(t: &TypeRef, acc: &mut Vec<Ty>, open_params: &[String]) {
        if let Some(fun) = &t.fun {
            let params: Vec<Ty> = fun
                .params
                .iter()
                .map(|p| {
                    // shallow: only nested fun handled by recursion
                    let mut nested = Vec::new();
                    from_type_ref(p, &mut nested, open_params);
                    if let Some(fun) = &p.fun {
                        let ps = fun
                            .params
                            .iter()
                            .map(|p| type_ref_to_ty_loose(p, open_params))
                            .collect();
                        let ret = type_ref_to_ty_loose(&fun.ret, open_params);
                        Ty::Fun {
                            params: ps,
                            ret: Box::new(ret),
                        }
                    } else {
                        type_ref_to_ty_loose(p, open_params)
                    }
                })
                .collect();
            let ret = type_ref_to_ty_loose(&fun.ret, open_params);
            acc.push(Ty::Fun {
                params,
                ret: Box::new(ret),
            });
            for p in &fun.params {
                from_type_ref(p, acc, open_params);
            }
            from_type_ref(&fun.ret, acc, open_params);
        }
        for a in &t.type_args {
            from_type_ref(a, acc, open_params);
        }
    }
    fn type_ref_to_ty_loose(t: &TypeRef, open_params: &[String]) -> Ty {
        if let Some(fun) = &t.fun {
            let params = fun
                .params
                .iter()
                .map(|p| type_ref_to_ty_loose(p, open_params))
                .collect();
            let ret = type_ref_to_ty_loose(&fun.ret, open_params);
            let base = Ty::Fun {
                params,
                ret: Box::new(ret),
            };
            return if t.nullable {
                Ty::Nullable(Box::new(base))
            } else {
                base
            };
        }
        let base = match t.name.name.as_str() {
            "Int" => Ty::Int,
            "Bool" => Ty::Bool,
            "String" => Ty::String,
            "Unit" => Ty::Unit,
            name if open_params.iter().any(|p| p == name) => Ty::TypeParam(name.into()),
            other => {
                if t.type_args.is_empty() {
                    Ty::Class(other.to_string())
                } else {
                    Ty::ClassApp {
                        name: other.to_string(),
                        args: t
                            .type_args
                            .iter()
                            .map(|a| type_ref_to_ty_loose(a, open_params))
                            .collect(),
                    }
                }
            }
        };
        if t.nullable {
            Ty::Nullable(Box::new(base))
        } else {
            base
        }
    }
    for f in &checked.ast.functions {
        let params: Vec<String> = f.type_params.iter().map(|p| p.name.name.clone()).collect();
        for p in &f.params {
            from_type_ref(&p.ty, &mut out, &params);
        }
        if let Some(rt) = &f.return_type {
            from_type_ref(rt, &mut out, &params);
        }
    }
    for c in &checked.ast.classes {
        let class_params: Vec<String> = c.type_params.iter().map(|p| p.name.name.clone()).collect();
        for field in &c.fields {
            from_type_ref(&field.ty, &mut out, &class_params);
        }
        for m in &c.methods {
            let mut params = class_params.clone();
            params.extend(m.type_params.iter().map(|p| p.name.name.clone()));
            for p in &m.params {
                from_type_ref(&p.ty, &mut out, &params);
            }
            if let Some(rt) = &m.return_type {
                from_type_ref(rt, &mut out, &params);
            }
        }
    }
    out
}

fn emit_fun_typedefs(out: &mut String, checked: &CheckedFile) {
    let mut seen = std::collections::HashSet::new();
    let mut tys = collect_fun_tys(checked);
    tys.sort_by_key(|t| t.mono_suffix());
    for ty in &tys {
        // Generic declarations contribute open `Fun<T, R>` annotations while
        // their concrete call sites contribute the monomorphized function
        // types.  An open function type has no valid C representation yet;
        // emitting it would produce identifiers such as `aura_cls_T`.
        if !matches!(ty, Ty::Fun { .. }) || ty.is_open() {
            continue;
        }
        let key = ty.mono_suffix();
        if seen.insert(key) {
            emit_fun_typedef(out, ty, checked);
        }
    }
    if !seen.is_empty() {
        out.push('\n');
    }
}

fn emit_capture_drop_helpers(out: &mut String, checked: &CheckedFile) {
    let mut array_keys = std::collections::BTreeSet::new();
    let mut has_fun = false;
    let mut has_obj = false;
    for captures in checked.lambda_captures.values() {
        for cap in captures {
            if !cap.by_ref {
                continue;
            }
            if is_array_capture_ty(&cap.ty) {
                array_keys.insert(cap.ty.mono_suffix());
            } else if is_fun_capture_ty(&cap.ty) {
                has_fun = true;
            } else if is_heap_class_capture_ty(&cap.ty, checked) {
                has_obj = true;
            }
        }
    }
    for key in array_keys {
        let c_ty = c_type_from_ty(
            &checked
                .lambda_captures
                .values()
                .flatten()
                .find(|c| c.by_ref && c.ty.mono_suffix() == key)
                .expect("array capture key must have a capture")
                .ty,
            checked,
        );
        let _ = writeln!(out, "static void aura_capture_drop_{key}(void *value) {{");
        let _ = writeln!(out, "  {c_ty} *__a = ({c_ty} *)value;");
        if crate::array_emit::is_array_of_heap_class(&key, checked) {
            out.push_str("  aura_gc_remove_array_root((void **)&__a->data);\n");
        }
        crate::array_emit::emit_array_contents_free(out, 2, "(*__a)", &key);
        out.push_str("  free(__a);\n}\n\n");
    }
    if has_fun {
        out.push_str("typedef struct { void *env; void *fn; } aura_capture_fun_payload;\n");
        out.push_str("static void aura_capture_drop_fun(void *value) {\n");
        out.push_str("  aura_capture_fun_payload *__f = (aura_capture_fun_payload *)value;\n");
        out.push_str("  aura_fun_env_free(__f->env);\n");
        out.push_str("  free(__f);\n}\n\n");
    }
    if has_obj {
        out.push_str("typedef struct { void *value; } aura_capture_obj_payload;\n");
        out.push_str("static void aura_capture_drop_obj(void *value) {\n");
        out.push_str("  aura_capture_obj_payload *__o = (aura_capture_obj_payload *)value;\n");
        out.push_str("  aura_gc_remove_root(&__o->value);\n");
        out.push_str("  free(__o);\n}\n\n");
    }
}

fn emit_lambda_fns(out: &mut String, checked: &CheckedFile, detector: bool) {
    if checked.lambda_tys.is_empty() {
        return;
    }
    let ids = build_lambda_ids(checked);
    let mut lambdas = collect_lambdas(&checked.ast);
    lambdas.sort_by_key(|l| l.span.start);
    for lam in &lambdas {
        let Some(&id) = ids.get(&lam.span.start) else {
            continue;
        };
        let Some(Ty::Fun { params, ret }) = checked.lambda_tys.get(&lam.span.start) else {
            continue;
        };
        let ret_c = if matches!(ret.as_ref(), Ty::Unit) {
            "void".to_string()
        } else {
            c_type_from_ty(ret, checked)
        };
        let mut parts = vec!["void *env".to_string()];
        for p in params {
            parts.push(c_type_from_ty(p, checked));
        }
        let _ = writeln!(
            out,
            "static {ret_c} aura_lambda_{id}({});",
            parts.join(", ")
        );
    }
    out.push('\n');
    emit_capture_drop_helpers(out, checked);

    // C10h/C12k/C12l/C12m/C13e: env structs for capturing lambdas (stable field order from sema).
    // Header: `__drop` + `__refs` (refcount for shared nested Fun envs / multi-owner free).
    // Array captures store a non-owning header view — drop must not free their buffers.
    // By-ref Int/Bool/String captures store aura_box_* pointers (retain on fill, release on drop).
    // Fun captures store fat pointer; retain nested env on fill, release on drop.
    for lam in &lambdas {
        let Some(&id) = ids.get(&lam.span.start) else {
            continue;
        };
        let captures = checked
            .lambda_captures
            .get(&lam.span.start)
            .map(|v| v.as_slice())
            .unwrap_or(&[]);
        if captures.is_empty() {
            continue;
        }
        let _ = writeln!(out, "typedef struct {{");
        let _ = writeln!(out, "  void (*__drop)(void *);");
        let _ = writeln!(out, "  int32_t __refs;");
        for cap in captures {
            let field_ty = c_capture_field_type(&cap.ty, cap.by_ref, checked);
            let _ = writeln!(out, "  {field_ty} {};", mangle_ident(&cap.name));
        }
        let _ = writeln!(out, "}} aura_lenv_{id};");
        // Per-env drop: remove GC roots for heap-class captures, release by-ref boxes,
        // release nested Fun envs, then free env only. C12l: never free Array view buffers.
        let _ = writeln!(out, "static void aura_lenv_{id}_drop(void *env) {{");
        let _ = writeln!(out, "  aura_lenv_{id} *__e = (aura_lenv_{id} *)env;");
        for cap in captures {
            let m = mangle_ident(&cap.name);
            if cap.by_ref {
                let rel = match &cap.ty {
                    Ty::Bool => format!("aura_box_bool_release(__e->{m});"),
                    Ty::String => format!("aura_box_str_release(__e->{m});"),
                    Ty::Int => format!("aura_box_i64_release(__e->{m});"),
                    _ => format!("aura_box_ptr_release(__e->{m});"),
                };
                let _ = writeln!(out, "  {rel}");
            } else if is_fun_capture_ty(&cap.ty) {
                // C13e: release retained nested env (no-op when env is NULL).
                let _ = writeln!(out, "  aura_fun_env_free(__e->{m}.env);");
            } else if is_heap_class_capture_ty(&cap.ty, checked) {
                let _ = writeln!(out, "  aura_gc_remove_root((void **)&__e->{m});");
            }
        }
        let _ = writeln!(out, "  free(__e);");
        let _ = writeln!(out, "}}\n");
    }

    for lam in lambdas {
        let Some(&id) = ids.get(&lam.span.start) else {
            continue;
        };
        let Some(fun_ty) = checked.lambda_tys.get(&lam.span.start) else {
            continue;
        };
        let Ty::Fun { params, ret } = fun_ty else {
            continue;
        };
        let captures = checked
            .lambda_captures
            .get(&lam.span.start)
            .map(|v| v.as_slice())
            .unwrap_or(&[]);
        let ret_c = match ret.as_ref() {
            Ty::Unit => "void".to_string(),
            r => c_type_from_ty(r, checked),
        };
        // C10h: first param is always env (fat-pointer convention).
        let mut param_parts = vec!["void *env".to_string()];
        for (i, pty) in params.iter().enumerate() {
            let pname = if let Some(p) = lam.params.get(i) {
                mangle_ident(&p.name.name)
            } else {
                format!("p{i}")
            };
            param_parts.push(format!("{} {pname}", c_type_from_ty(pty, checked)));
        }
        let ps = param_parts.join(", ");
        let _ = writeln!(out, "static {ret_c} aura_lambda_{id}({ps}) {{");
        if captures.is_empty() {
            out.push_str("  (void)env;\n");
        } else {
            let _ = writeln!(out, "  aura_lenv_{id} *__e = (aura_lenv_{id} *)env;");
            for cap in captures {
                let m = mangle_ident(&cap.name);
                let field_ty = c_capture_field_type(&cap.ty, cap.by_ref, checked);
                let _ = writeln!(out, "  {field_ty} {m} = __e->{m};");
            }
        }
        let ret_key = Some(ret.mono_suffix());
        let mut ctx = EmitCtx {
            checked,
            detector,
            method_class: None,
            type_params: Vec::new(),
            type_args: Vec::new(),
            locals: vec![HashMap::new()],
            array_owners: vec![std::collections::HashSet::new()],
            fun_owners: vec![std::collections::HashSet::new()],
            string_owners: vec![std::collections::HashSet::new()],
            channel_owners: vec![std::collections::HashSet::new()],
            box_locals: vec![std::collections::HashSet::new()],
            box_owners: vec![std::collections::HashSet::new()],
            gc_roots: vec![std::collections::HashSet::new()],
            array_gc_roots: vec![std::collections::HashSet::new()],
            return_key: ret_key,
            lambda_ids: ids.clone(),
            spawn_params: HashSet::new(),
        };
        // C12l: Array captures are non-owning views — do not mark array_owner
        // (env/header copy only; outer scope frees the buffer).
        // C12m: by-ref captures are box pointers; mark so reads/writes use ->value.
        for cap in captures {
            ctx.define_local(&cap.name, cap.ty.mono_suffix());
            if cap.by_ref {
                ctx.mark_box_local(&cap.name);
            }
        }
        for (i, p) in lam.params.iter().enumerate() {
            let key = params
                .get(i)
                .map(|t| t.mono_suffix())
                .unwrap_or_else(|| "Int".into());
            ctx.define_local(&p.name.name, key);
        }
        match &lam.body {
            LambdaBody::Expr(body) => {
                let body_c = crate::expr::emit_expr(body, &mut ctx);
                if matches!(ret.as_ref(), Ty::Unit) {
                    let _ = writeln!(out, "  {body_c};");
                } else {
                    let _ = writeln!(out, "  return {body_c};");
                }
            }
            LambdaBody::Block(block) => {
                // C10g: emit statements; returns handled by Stmt::Return.
                emit_block(out, block, 1, &mut ctx);
                // Unreachable fallback if all paths return (mirrors fun bodies).
                match ret.as_ref() {
                    Ty::Unit => {}
                    Ty::Int => out.push_str("  return INT64_C(0); /* fallback */\n"),
                    Ty::Bool => out.push_str("  return false; /* fallback */\n"),
                    Ty::String => out.push_str("  return \"\"; /* fallback */\n"),
                    other => {
                        let ct = c_type_from_ty(other, checked);
                        if ct != "void" {
                            let _ = writeln!(out, "  return ({ct}){{0}}; /* fallback */");
                        }
                    }
                }
            }
        }
        out.push_str("}\n\n");
    }
}

pub(crate) fn emit_fun(
    out: &mut String,
    f: &FunDecl,
    checked: &CheckedFile,
    args: &[Ty],
    detector: bool,
) {
    let params: Vec<String> = f.type_params.iter().map(|p| p.name.name.clone()).collect();
    let _ = writeln!(out, "{} {{", c_fun_signature(f, checked, args));
    let pkg = fun_decl_package(f, checked);
    // std.io console + file intrinsics (runtime `aura_*`).
    if pkg == "std.io" {
        match (f.name.name.as_str(), f.params.len()) {
            ("print", 1) => {
                let a = mangle_ident(&f.params[0].name.name);
                let _ = writeln!(out, "  aura_print({a});");
                out.push_str("}\n");
                return;
            }
            ("println", 1) => {
                let a = mangle_ident(&f.params[0].name.name);
                let _ = writeln!(out, "  aura_println({a});");
                out.push_str("}\n");
                return;
            }
            ("eprint", 1) => {
                let a = mangle_ident(&f.params[0].name.name);
                let _ = writeln!(out, "  aura_eprint({a});");
                out.push_str("}\n");
                return;
            }
            ("eprintln", 1) => {
                let a = mangle_ident(&f.params[0].name.name);
                let _ = writeln!(out, "  aura_eprintln({a});");
                out.push_str("}\n");
                return;
            }
            ("readFile", 1) => {
                let a = mangle_ident(&f.params[0].name.name);
                let _ = writeln!(out, "  return aura_read_file({a});");
                out.push_str("}\n");
                return;
            }
            // C12p: soft read — NULL on missing path / I/O / oversize / NUL.
            ("tryReadFile", 1) => {
                let a = mangle_ident(&f.params[0].name.name);
                let _ = writeln!(out, "  return aura_try_read_file({a});");
                out.push_str("}\n");
                return;
            }
            ("writeFile", 2) => {
                let p = mangle_ident(&f.params[0].name.name);
                let c = mangle_ident(&f.params[1].name.name);
                let _ = writeln!(out, "  aura_write_file({p}, {c});");
                out.push_str("}\n");
                return;
            }
            // C13o: soft write — false on empty path / I/O fail (no throw).
            ("tryWriteFile", 2) => {
                let p = mangle_ident(&f.params[0].name.name);
                let c = mangle_ident(&f.params[1].name.name);
                let _ = writeln!(out, "  return aura_try_write_file({p}, {c});");
                out.push_str("}\n");
                return;
            }
            ("appendFile", 2) => {
                let p = mangle_ident(&f.params[0].name.name);
                let c = mangle_ident(&f.params[1].name.name);
                let _ = writeln!(out, "  aura_append_file({p}, {c});");
                out.push_str("}\n");
                return;
            }
            ("fileExists", 1) => {
                let a = mangle_ident(&f.params[0].name.name);
                let _ = writeln!(out, "  return aura_file_exists({a});");
                out.push_str("}\n");
                return;
            }
            ("fileSize", 1) => {
                let a = mangle_ident(&f.params[0].name.name);
                let _ = writeln!(out, "  return aura_file_size({a});");
                out.push_str("}\n");
                return;
            }
            // C12b: std.io.args() → Array<String> from stashed argc/argv.
            ("args", 0) => {
                let arr_ty = c_class_type("Array_String");
                let ctor = c_ctor_name("Array_String");
                let _ = writeln!(out, "  int64_t __n = aura_args_count();");
                let _ = writeln!(out, "  {arr_ty} __a = {ctor}(__n);");
                out.push_str("  for (int64_t __i = 0; __i < __n; __i++) {\n");
                out.push_str("    __a.data[__i] = aura_args_get(__i);\n");
                out.push_str("  }\n");
                out.push_str("  return __a;\n");
                out.push_str("}\n");
                return;
            }
            // C12d: stdin line / whole-stdin (NULL = EOF for readLine).
            ("readLine", 0) => {
                out.push_str("  return aura_read_line();\n");
                out.push_str("}\n");
                return;
            }
            ("readAllStdin", 0) => {
                out.push_str("  return aura_read_all_stdin();\n");
                out.push_str("}\n");
                return;
            }
            // C12e: std.io.exit(code) → process exit (does not return).
            ("exit", 1) => {
                let a = mangle_ident(&f.params[0].name.name);
                let _ = writeln!(out, "  aura_exit({a});");
                out.push_str("}\n");
                return;
            }
            _ => {}
        }
    }
    // C4h: std.assert.assert → aura_assert.
    if pkg == "std.assert" && f.name.name == "assert" && f.params.len() == 1 {
        let arg = mangle_ident(&f.params[0].name.name);
        let _ = writeln!(out, "  aura_assert({arg});");
        out.push_str("}\n");
        return;
    }
    let ret_key = f
        .return_type
        .as_ref()
        .map(|t| type_ref_local_key_expand(t, &params, args, checked));
    let mut ctx = EmitCtx {
        checked,
        detector,
        method_class: None,
        type_params: params.clone(),
        type_args: args.to_vec(),
        locals: vec![HashMap::new()],
        array_owners: vec![std::collections::HashSet::new()],
        fun_owners: vec![std::collections::HashSet::new()],
        string_owners: vec![std::collections::HashSet::new()],
        channel_owners: vec![std::collections::HashSet::new()],
        box_locals: vec![std::collections::HashSet::new()],
        box_owners: vec![std::collections::HashSet::new()],
        gc_roots: vec![std::collections::HashSet::new()],
        array_gc_roots: vec![std::collections::HashSet::new()],
        return_key: ret_key,
        lambda_ids: build_lambda_ids(checked),
        spawn_params: f.params.iter().map(|p| p.name.name.clone()).collect(),
    };
    for p in &f.params {
        let key = type_ref_local_key_expand(&p.ty, &params, args, checked);
        let mono_key = full_type_mono(&key, checked);
        ctx.define_local(&p.name.name, mono_key.clone());
        // C6b/C21d: owning Array params own the buffer; `ref Array<T>` params
        // are header views over their caller's storage and must not free it.
        if !p.ty.reference && crate::array_emit::is_array_type_key(&key) {
            ctx.mark_array_owner(&p.name.name);
        }
        // Fun params own capture env (caller moves).
        if is_fun_type_key(&key) {
            ctx.mark_fun_owner(&p.name.name);
        }
        // C5g: heap-class params are GC roots for the function body.
        if is_heap_class_mono(&mono_key, checked) {
            ctx.mark_gc_root(&p.name.name);
            let n = mangle_ident(&p.name.name);
            let _ = writeln!(out, "  aura_gc_add_root((void **)&{n});");
        }
        // C6e: Array-of-class params keep element GC pointers alive.
        if crate::array_emit::is_array_of_heap_class(&mono_key, checked) {
            ctx.mark_array_gc_root(&p.name.name);
            let n = mangle_ident(&p.name.name);
            let _ = writeln!(
                out,
                "  aura_gc_add_array_root((void **)&{n}.data, &{n}.len);"
            );
        }
    }
    emit_block(out, &f.body, 1, &mut ctx);
    // Function parameters live in the outer emission scope, so the block
    // cleanup above does not release owning Array parameters that were not
    // moved or returned. Keep the parameter ownership invariant symmetric
    // with the nested-block cleanup path.
    let array_owners = ctx.array_owners_all();
    crate::stmt::emit_free_array_owners(out, 1, &ctx, &array_owners);
    // Drop param roots when leaving the function.
    for name in ctx.array_gc_roots_all() {
        let n = mangle_ident(&name);
        let _ = writeln!(out, "  aura_gc_remove_array_root((void **)&{n}.data);");
    }
    for name in ctx.gc_roots_all() {
        let n = if name == "this" {
            "this".to_string()
        } else {
            mangle_ident(&name)
        };
        let _ = writeln!(out, "  aura_gc_remove_root((void **)&{n});");
    }
    // Free remaining Fun capture envs (params / locals not transferred by return).
    crate::stmt::emit_free_fun_owners(out, 1, &ctx, &ctx.fun_owners_all());
    // C12m: release remaining by-ref boxes (outer retain).
    crate::stmt::emit_release_box_locals(out, 1, &ctx, &ctx.box_owners_all());
    emit_return_fallback(out, &f.return_type, checked, &params, args);
    out.push_str("}\n");
}
