//! Top-level C translation unit emission.

use std::collections::HashMap;
use std::fmt::Write as _;

use aura_ast::*;
use aura_sema::{CheckedFile, Ty};

use crate::array_emit::{emit_array_mono, is_array_mono};
use crate::class_emit::*;
use crate::ctx::{EmitCtx, EmitOptions};
use crate::enum_emit::*;
use crate::iface::*;
use crate::names::*;
use crate::stmt::{emit_block, emit_return_fallback};

pub fn emit_c(checked: &CheckedFile) -> String {
    emit_c_with(checked, EmitOptions::default())
}

/// Emit C with options (normal binary or test harness).
pub fn emit_c_with(checked: &CheckedFile, opts: EmitOptions) -> String {
    let mut out = String::new();
    out.push_str("/* generated by aura-codegen (C3 C backend) */\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <stdlib.h>\n");
    out.push_str("#include <stdio.h>\n");
    out.push_str("#include <setjmp.h>\n");
    out.push_str("void aura_println(const char *s);\n");
    out.push_str("void aura_assert(_Bool cond);\n");
    out.push_str("void aura_assert_eq_int(int64_t a, int64_t b);\n");
    out.push_str("void aura_assert_eq_string(const char *a, const char *b);\n");
    out.push_str("void aura_assert_eq_bool(_Bool a, _Bool b);\n");
    out.push_str("void aura_try_enter(jmp_buf *buf);\n");
    out.push_str("void aura_try_leave(void);\n");
    out.push_str("void aura_throw_string(const char *s);\n");
    out.push_str("void aura_throw_int(int64_t v);\n");
    out.push_str("void aura_throw_bool(_Bool v);\n");
    out.push_str("void aura_throw_obj(const char *type_name, void *obj);\n");
    out.push_str("int aura_ex_matches(const char *type_name);\n");
    out.push_str("const char *aura_ex_as_string(void);\n");
    out.push_str("int64_t aura_ex_as_int(void);\n");
    out.push_str("_Bool aura_ex_as_bool(void);\n");
    out.push_str("void *aura_ex_as_obj(void);\n");
    out.push_str("void aura_ex_clear(void);\n");
    out.push_str("void aura_ex_rethrow(void);\n");
    out.push_str("int aura_main(void);\n\n");

    // Stable class tags for interface dispatch (non-generic only)
    let tagged: Vec<_> = checked
        .ast
        .classes
        .iter()
        .filter(|c| c.type_params.is_empty())
        .collect();
    if !tagged.is_empty() {
        out.push_str("enum {\n");
        for (i, c) in tagged.iter().enumerate() {
            let _ = writeln!(out, "  AURA_TAG_{} = {},", c.name.name, i);
        }
        out.push_str("  AURA_TAG__COUNT\n};\n\n");
    }

    // Class typedefs — non-generic classes + monomorphized generic classes
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_typedef(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            if let Some(elem) = args.first() {
                // Typedef + methods emitted later with other Array defs (need one place).
                let _ = elem;
            }
            continue;
        }
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_typedef(&mut out, checked, c, args);
        }
    }
    // Builtin Array<T> mono (typedef + ctor/get/set)
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            if let Some(elem) = args.first() {
                emit_array_mono(&mut out, elem);
            }
        }
    }

    // Enum tagged unions
    for e in &checked.ast.enums {
        if e.type_params.is_empty() {
            emit_enum_typedef(&mut out, checked, e, &[]);
        }
    }
    for (name, args) in &checked.mono_enums {
        if let Some(e) = checked.ast.enums.iter().find(|e| e.name.name == *name) {
            emit_enum_typedef(&mut out, checked, e, args);
        }
    }

    // Interface tagged unions
    for iface in &checked.ast.interfaces {
        let impls = implementors(checked, &iface.name.name);
        let _ = writeln!(
            out,
            "typedef struct {} {{",
            c_iface_type(&iface.name.name)
        );
        out.push_str("  int tag;\n  union {\n");
        for c in &impls {
            let _ = writeln!(
                out,
                "    {} as_{};",
                c_class_type(&c.name.name),
                c.name.name
            );
        }
        if impls.is_empty() {
            out.push_str("    char _empty;\n");
        }
        let _ = writeln!(out, "  }} data;\n}} {};\n", c_iface_type(&iface.name.name));
    }

    // Forward decls
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_forwards(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue; // Array defs already fully emitted
        }
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_forwards(&mut out, checked, c, args);
        }
    }
    for e in &checked.ast.enums {
        if e.type_params.is_empty() {
            emit_enum_forwards(&mut out, checked, e, &[]);
        }
    }
    for (name, args) in &checked.mono_enums {
        if let Some(e) = checked.ast.enums.iter().find(|e| e.name.name == *name) {
            emit_enum_forwards(&mut out, checked, e, args);
        }
    }
    for iface in &checked.ast.interfaces {
        for m in &iface.methods {
            let _ = writeln!(
                out,
                "{};",
                c_iface_method_signature(&iface.name.name, m, checked)
            );
        }
    }
    for f in &checked.ast.functions {
        if f.name.name == "main" {
            continue;
        }
        if f.type_params.is_empty() {
            let _ = writeln!(out, "{};", c_fun_signature(f, checked, &[]));
        }
    }
    for (name, args) in &checked.mono_funs {
        if let Some(f) = checked.ast.functions.iter().find(|f| f.name.name == *name) {
            let _ = writeln!(out, "{};", c_fun_signature(f, checked, args));
        }
    }
    out.push('\n');

    // Definitions
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_defs(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_defs(&mut out, checked, c, args);
        }
    }

    for e in &checked.ast.enums {
        if e.type_params.is_empty() {
            emit_enum_defs(&mut out, checked, e, &[]);
        }
    }
    for (name, args) in &checked.mono_enums {
        if let Some(e) = checked.ast.enums.iter().find(|e| e.name.name == *name) {
            emit_enum_defs(&mut out, checked, e, args);
        }
    }

    for iface in &checked.ast.interfaces {
        for m in &iface.methods {
            emit_iface_dispatch(&mut out, checked, &iface.name.name, m);
            out.push('\n');
        }
    }

    for f in &checked.ast.functions {
        if f.type_params.is_empty() {
            emit_fun(&mut out, f, checked, &[]);
            out.push('\n');
        }
    }
    for (name, args) in &checked.mono_funs {
        if let Some(f) = checked.ast.functions.iter().find(|f| f.name.name == *name) {
            emit_fun(&mut out, f, checked, args);
            out.push('\n');
        }
    }

    if opts.test {
        emit_test_main(&mut out, checked);
    } else {
        out.push_str("int aura_main(void) {\n");
        if checked.ast.functions.iter().any(|f| f.name.name == "main") {
            out.push_str("  aura_fn_main();\n");
        }
        out.push_str("  return 0;\n}\n");
    }
    out
}

pub(crate) fn emit_test_main(out: &mut String, checked: &CheckedFile) {
    let tests: Vec<_> = checked
        .ast
        .functions
        .iter()
        .filter(|f| f.is_test)
        .collect();
    out.push_str("int aura_main(void) {\n");
    out.push_str("  int failed = 0;\n");
    out.push_str("  int ran = 0;\n");
    if tests.is_empty() {
        out.push_str("  puts(\"no tests\");\n");
        out.push_str("  return 0;\n}\n");
        return;
    }
    for t in &tests {
        let name = &t.name.name;
        let fn_c = c_fun_name(name, &[]);
        let _ = writeln!(out, "  /* test {name} */");
        out.push_str("  {\n");
        out.push_str("    jmp_buf __tjb;\n");
        let _ = writeln!(out, "    printf(\"test {name} ... \");");
        out.push_str("    fflush(stdout);\n");
        out.push_str("    ran++;\n");
        out.push_str("    if (setjmp(__tjb) == 0) {\n");
        out.push_str("      aura_try_enter(&__tjb);\n");
        let _ = writeln!(out, "      {fn_c}();");
        out.push_str("      aura_try_leave();\n");
        out.push_str("      puts(\"ok\");\n");
        out.push_str("    } else {\n");
        out.push_str("      const char *__msg = aura_ex_matches(\"String\") ? aura_ex_as_string() : \"exception\";\n");
        out.push_str("      printf(\"FAILED (%s)\\n\", __msg ? __msg : \"?\");\n");
        out.push_str("      aura_ex_clear();\n");
        out.push_str("      aura_try_leave();\n");
        out.push_str("      failed++;\n");
        out.push_str("    }\n");
        out.push_str("  }\n");
    }
    out.push_str("  printf(\"%d passed, %d failed\\n\", ran - failed, failed);\n");
    out.push_str("  return failed ? 1 : 0;\n}\n");
}

pub(crate) fn emit_fun(out: &mut String, f: &FunDecl, checked: &CheckedFile, args: &[Ty]) {
    let params: Vec<String> = f.type_params.iter().map(|p| p.name.name.clone()).collect();
    let _ = writeln!(out, "{} {{", c_fun_signature(f, checked, args));
    let mut ctx = EmitCtx {
        checked,
        method_class: None,
        type_params: params.clone(),
        type_args: args.to_vec(),
        locals: vec![HashMap::new()],
    };
    for p in &f.params {
        ctx.define_local(
            &p.name.name,
            type_ref_local_key(&p.ty, &params, args),
        );
    }
    emit_block(out, &f.body, 1, &mut ctx);
    emit_return_fallback(out, &f.return_type, checked, &params, args);
    out.push_str("}\n");
}
