//! Top-level C translation unit emission.

use std::collections::HashMap;
use std::fmt::Write as _;

use aura_ast::*;
use aura_sema::{CheckedFile, Ty};

use crate::array_emit::{emit_array_mono, is_array_mono};
use crate::class_emit::*;
use crate::ctx::{EmitCtx, EmitOptions};
use crate::enum_emit::*;
use crate::expr::full_type_mono;
use crate::iface::*;
use crate::names::*;
use crate::stmt::{emit_block, emit_return_fallback};

pub fn emit_c(checked: &CheckedFile) -> String {
    emit_c_with(checked, EmitOptions::default())
}

/// Emit C with options (normal binary or test harness).
pub fn emit_c_with(checked: &CheckedFile, opts: EmitOptions) -> String {
    let mut out = String::new();
    out.push_str("/* generated by aura-codegen (C3 C backend) */\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <stdlib.h>\n");
    out.push_str("#include <stdio.h>\n");
    out.push_str("#include <string.h>\n");
    out.push_str("#include <setjmp.h>\n");
    out.push_str("void aura_println(const char *s);\n");
    out.push_str("void aura_assert(_Bool cond);\n");
    out.push_str("void aura_assert_eq_int(int64_t a, int64_t b);\n");
    out.push_str("void aura_assert_eq_string(const char *a, const char *b);\n");
    out.push_str("void aura_assert_eq_bool(_Bool a, _Bool b);\n");
    out.push_str("void aura_try_enter(jmp_buf *buf);\n");
    out.push_str("void aura_try_leave(void);\n");
    out.push_str("void aura_throw_string(const char *s);\n");
    out.push_str("void aura_throw_int(int64_t v);\n");
    out.push_str("void aura_throw_bool(_Bool v);\n");
    out.push_str("void aura_throw_obj(const char *type_name, void *obj);\n");
    out.push_str("int aura_ex_matches(const char *type_name);\n");
    out.push_str("const char *aura_ex_as_string(void);\n");
    out.push_str("int64_t aura_ex_as_int(void);\n");
    out.push_str("_Bool aura_ex_as_bool(void);\n");
    out.push_str("void *aura_ex_as_obj(void);\n");
    out.push_str("void aura_ex_clear(void);\n");
    out.push_str("void aura_ex_rethrow(void);\n");
    out.push_str("void *aura_gc_alloc(size_t size);\n");
    out.push_str("void aura_gc_add_root(void **slot);\n");
    out.push_str("void aura_gc_remove_root(void **slot);\n");
    out.push_str("void aura_gc_add_array_root(void **data_slot, int64_t *len_slot);\n");
    out.push_str("void aura_gc_remove_array_root(void **data_slot);\n");
    out.push_str("void aura_gc_collect(void);\n");
    out.push_str("void aura_gc_shutdown(void);\n");
    out.push_str("int aura_main(void);\n\n");

    // Stable class tags for interface dispatch (non-generic only)
    let tagged: Vec<_> = checked
        .ast
        .classes
        .iter()
        .filter(|c| c.type_params.is_empty())
        .collect();
    if !tagged.is_empty() {
        out.push_str("enum {\n");
        for (i, c) in tagged.iter().enumerate() {
            let pkg = class_decl_package(c, checked);
            let mono = type_mono(&pkg, &c.name.name, &[]);
            let _ = writeln!(out, "  AURA_TAG_{mono} = {i},");
        }
        out.push_str("  AURA_TAG__COUNT\n};\n\n");
    }

    // Class typedefs — non-generic classes + monomorphized generic classes.
    // C4u: incomplete struct forwards so nested monomorph field pointers compile
    // regardless of alphabetical mono_classes order (Outer_String → Wrapper_String).
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            let pkg = class_decl_package(c, checked);
            let mono = type_mono(&pkg, &c.name.name, &[]);
            let _ = writeln!(
                out,
                "typedef struct {} {};",
                c_class_type(&mono),
                c_class_type(&mono)
            );
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            let pkg = class_decl_package(c, checked);
            let mono = type_mono(&pkg, &c.name.name, args);
            let _ = writeln!(
                out,
                "typedef struct {} {};",
                c_class_type(&mono),
                c_class_type(&mono)
            );
        }
    }
    // C6g: enums + value structs must be complete before Array monomorphs
    // (Array stores them by value / sizeof). Heap classes stay incomplete here
    // so Array-of-class can use pointers only.
    for e in &checked.ast.enums {
        if e.type_params.is_empty() {
            emit_enum_typedef(&mut out, checked, e, &[]);
        }
    }
    for (name, args) in &checked.mono_enums {
        if let Some(e) = checked.ast.enums.iter().find(|e| e.name.name == *name) {
            emit_enum_typedef(&mut out, checked, e, args);
        }
    }
    for c in &checked.ast.classes {
        if c.type_params.is_empty() && c.kind == NominalKind::Struct {
            emit_class_typedef(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked
            .ast
            .classes
            .iter()
            .find(|c| c.name.name == *name && c.kind == NominalKind::Struct)
        {
            emit_class_typedef(&mut out, checked, c, args);
        }
    }

    // C6f: Array monomorphs before heap class bodies so classes may embed Array by value.
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            if let Some(elem) = args.first() {
                emit_array_mono(&mut out, elem, checked);
            }
        }
    }
    for c in &checked.ast.classes {
        if c.type_params.is_empty() && c.kind == NominalKind::Class {
            emit_class_typedef(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked
            .ast
            .classes
            .iter()
            .find(|c| c.name.name == *name && c.kind == NominalKind::Class)
        {
            emit_class_typedef(&mut out, checked, c, args);
        }
    }

    // Interface tagged unions (C4d: package-prefixed iface mono)
    for iface in &checked.ast.interfaces {
        let imono = iface_mono(iface, checked);
        let impls = implementors_for_iface(checked, iface);
        let _ = writeln!(out, "typedef struct {} {{", c_iface_type(&imono));
        out.push_str("  int tag;\n  union {\n");
        for c in &impls {
            let pkg = class_decl_package(c, checked);
            let mono = type_mono(&pkg, &c.name.name, &[]);
            // C3y: heap classes stored as pointers inside the interface union.
            let field_ty = if is_heap_class_decl(c) {
                format!("{} *", c_class_type(&mono))
            } else {
                c_class_type(&mono)
            };
            let _ = writeln!(out, "    {field_ty} as_{mono};");
        }
        if impls.is_empty() {
            out.push_str("    char _empty;\n");
        }
        let _ = writeln!(out, "  }} data;\n}} {};\n", c_iface_type(&imono));
    }

    // Forward decls
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_forwards(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue; // Array defs already fully emitted
        }
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_forwards(&mut out, checked, c, args);
        }
    }
    for e in &checked.ast.enums {
        if e.type_params.is_empty() {
            emit_enum_forwards(&mut out, checked, e, &[]);
        }
    }
    for (name, args) in &checked.mono_enums {
        if let Some(e) = checked.ast.enums.iter().find(|e| e.name.name == *name) {
            emit_enum_forwards(&mut out, checked, e, args);
        }
    }
    for iface in &checked.ast.interfaces {
        let imono = iface_mono(iface, checked);
        for m in &iface.methods {
            let _ = writeln!(out, "{};", c_iface_method_signature(&imono, m, checked));
        }
    }
    for f in &checked.ast.functions {
        if f.name.name == "main" {
            continue;
        }
        if f.type_params.is_empty() {
            let _ = writeln!(out, "{};", c_fun_signature(f, checked, &[]));
        }
    }
    for (name, args) in &checked.mono_funs {
        if let Some(f) = checked.ast.functions.iter().find(|f| f.name.name == *name) {
            let _ = writeln!(out, "{};", c_fun_signature(f, checked, args));
        }
    }
    out.push('\n');

    // Definitions
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_defs(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if is_array_mono(name) {
            continue;
        }
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_defs(&mut out, checked, c, args);
        }
    }

    for e in &checked.ast.enums {
        if e.type_params.is_empty() {
            emit_enum_defs(&mut out, checked, e, &[]);
        }
    }
    for (name, args) in &checked.mono_enums {
        if let Some(e) = checked.ast.enums.iter().find(|e| e.name.name == *name) {
            emit_enum_defs(&mut out, checked, e, args);
        }
    }

    for iface in &checked.ast.interfaces {
        for m in &iface.methods {
            emit_iface_dispatch(&mut out, checked, iface, m);
            out.push('\n');
        }
    }

    for f in &checked.ast.functions {
        if f.type_params.is_empty() {
            emit_fun(&mut out, f, checked, &[]);
            out.push('\n');
        }
    }
    for (name, args) in &checked.mono_funs {
        if let Some(f) = checked.ast.functions.iter().find(|f| f.name.name == *name) {
            emit_fun(&mut out, f, checked, args);
            out.push('\n');
        }
    }

    if opts.test {
        emit_test_main(&mut out, checked);
    } else {
        out.push_str("int aura_main(void) {\n");
        if checked.ast.functions.iter().any(|f| f.name.name == "main") {
            out.push_str("  aura_fn_main();\n");
        }
        out.push_str("  return 0;\n}\n");
    }
    out
}

pub(crate) fn emit_test_main(out: &mut String, checked: &CheckedFile) {
    let tests: Vec<_> = checked.ast.functions.iter().filter(|f| f.is_test).collect();
    out.push_str("int aura_main(void) {\n");
    out.push_str("  int failed = 0;\n");
    out.push_str("  int ran = 0;\n");
    if tests.is_empty() {
        out.push_str("  puts(\"no tests\");\n");
        out.push_str("  return 0;\n}\n");
        return;
    }
    for t in &tests {
        let name = &t.name.name;
        let pkg = fun_decl_package(t, checked);
        let fn_c = c_fun_name(&pkg, name, &[]);
        let _ = writeln!(out, "  /* test {name} */");
        out.push_str("  {\n");
        out.push_str("    jmp_buf __tjb;\n");
        let _ = writeln!(out, "    printf(\"test {name} ... \");");
        out.push_str("    fflush(stdout);\n");
        out.push_str("    ran++;\n");
        out.push_str("    if (setjmp(__tjb) == 0) {\n");
        out.push_str("      aura_try_enter(&__tjb);\n");
        let _ = writeln!(out, "      {fn_c}();");
        out.push_str("      aura_try_leave();\n");
        out.push_str("      puts(\"ok\");\n");
        out.push_str("    } else {\n");
        out.push_str("      const char *__msg = aura_ex_matches(\"String\") ? aura_ex_as_string() : \"exception\";\n");
        out.push_str("      printf(\"FAILED (%s)\\n\", __msg ? __msg : \"?\");\n");
        out.push_str("      aura_ex_clear();\n");
        out.push_str("      aura_try_leave();\n");
        out.push_str("      failed++;\n");
        out.push_str("    }\n");
        out.push_str("  }\n");
    }
    out.push_str("  printf(\"%d passed, %d failed\\n\", ran - failed, failed);\n");
    out.push_str("  return failed ? 1 : 0;\n}\n");
}

pub(crate) fn emit_fun(out: &mut String, f: &FunDecl, checked: &CheckedFile, args: &[Ty]) {
    let params: Vec<String> = f.type_params.iter().map(|p| p.name.name.clone()).collect();
    let _ = writeln!(out, "{} {{", c_fun_signature(f, checked, args));
    let pkg = fun_decl_package(f, checked);
    // C3z: std.io.println is an intrinsic wrapping aura_println.
    if pkg == "std.io" && f.name.name == "println" && f.params.len() == 1 {
        let arg = mangle_ident(&f.params[0].name.name);
        let _ = writeln!(out, "  aura_println({arg});");
        out.push_str("}\n");
        return;
    }
    // C4h: std.assert.assert → aura_assert.
    if pkg == "std.assert" && f.name.name == "assert" && f.params.len() == 1 {
        let arg = mangle_ident(&f.params[0].name.name);
        let _ = writeln!(out, "  aura_assert({arg});");
        out.push_str("}\n");
        return;
    }
    let mut ctx = EmitCtx {
        checked,
        method_class: None,
        type_params: params.clone(),
        type_args: args.to_vec(),
        locals: vec![HashMap::new()],
        array_owners: vec![std::collections::HashSet::new()],
        gc_roots: vec![std::collections::HashSet::new()],
        array_gc_roots: vec![std::collections::HashSet::new()],
    };
    for p in &f.params {
        let key = type_ref_local_key(&p.ty, &params, args);
        let mono_key = full_type_mono(&key, checked);
        ctx.define_local(&p.name.name, mono_key.clone());
        // C6b: Array params own the buffer (caller moves or passes a fresh Array).
        if crate::array_emit::is_array_type_key(&key) {
            ctx.mark_array_owner(&p.name.name);
        }
        // C5g: heap-class params are GC roots for the function body.
        if is_heap_class_mono(&mono_key, checked) {
            ctx.mark_gc_root(&p.name.name);
            let n = mangle_ident(&p.name.name);
            let _ = writeln!(out, "  aura_gc_add_root((void **)&{n});");
        }
        // C6e: Array-of-class params keep element GC pointers alive.
        if crate::array_emit::is_array_of_heap_class(&mono_key, checked) {
            ctx.mark_array_gc_root(&p.name.name);
            let n = mangle_ident(&p.name.name);
            let _ = writeln!(
                out,
                "  aura_gc_add_array_root((void **)&{n}.data, &{n}.len);"
            );
        }
    }
    emit_block(out, &f.body, 1, &mut ctx);
    // Drop param roots when leaving the function.
    for name in ctx.array_gc_roots_all() {
        let n = mangle_ident(&name);
        let _ = writeln!(out, "  aura_gc_remove_array_root((void **)&{n}.data);");
    }
    for name in ctx.gc_roots_all() {
        let n = if name == "this" {
            "this".to_string()
        } else {
            mangle_ident(&name)
        };
        let _ = writeln!(out, "  aura_gc_remove_root((void **)&{n});");
    }
    emit_return_fallback(out, &f.return_type, checked, &params, args);
    out.push_str("}\n");
}
