//! Emit C99 for Aura C0/C1 programs and shell out to a C compiler.
//!
//! This is the **C1** ship path until LLVM IR lands (RFC-004). The runtime
//! (`runtime/aura_rt.c`) provides `println` and process entry.

use aura_ast::*;
use aura_sema::{check_file, CheckedFile, SemaError};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug)]
pub enum CodegenError {
    Sema(SemaError),
    Io(String),
    Compile(String),
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodegenError::Sema(e) => write!(f, "{e}"),
            CodegenError::Io(e) | CodegenError::Compile(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for CodegenError {}

impl From<SemaError> for CodegenError {
    fn from(e: SemaError) -> Self {
        CodegenError::Sema(e)
    }
}

/// Emit a complete C translation unit for the checked file.
pub fn emit_c(checked: &CheckedFile) -> String {
    let mut out = String::new();
    out.push_str("/* generated by aura-codegen (C1 C backend) */\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("void aura_println(const char *s);\n");
    out.push_str("int aura_main(void);\n\n");

    // Forward declarations for user functions (except main)
    for f in &checked.ast.functions {
        if f.name.name == "main" {
            continue;
        }
        let _ = writeln!(out, "{};", c_fun_signature(f));
    }
    out.push('\n');

    for f in &checked.ast.functions {
        emit_fun(&mut out, f);
        out.push('\n');
    }

    // C entry: call Aura main (Unit return)
    out.push_str("int aura_main(void) {\n");
    if checked.ast.functions.iter().any(|f| f.name.name == "main") {
        out.push_str("  aura_fn_main();\n");
    }
    out.push_str("  return 0;\n}\n");
    out
}

fn c_fun_name(name: &str) -> String {
    if name == "main" {
        "aura_fn_main".into()
    } else if name == "println" {
        "aura_println".into()
    } else {
        format!("aura_fn_{name}")
    }
}

fn c_type(ty: &TypeRef) -> &'static str {
    // Only C0+ types
    match (ty.name.name.as_str(), ty.nullable) {
        ("Int", false) => "int64_t",
        ("Bool", false) => "bool",
        ("String", false) => "const char *",
        ("String", true) => "const char *",
        ("Unit", false) => "void",
        ("Int", true) => "/* Int? unsupported in C1 */ int64_t",
        ("Bool", true) => "/* Bool? unsupported in C1 */ bool",
        _ => "void",
    }
}

fn c_type_from_opt(ret: &Option<TypeRef>) -> &'static str {
    match ret {
        None => "void",
        Some(t) => c_type(t),
    }
}

fn c_fun_signature(f: &FunDecl) -> String {
    let ret = c_type_from_opt(&f.return_type);
    let params = if f.params.is_empty() {
        "void".into()
    } else {
        f.params
            .iter()
            .map(|p| format!("{} {}", c_type(&p.ty), mangle_ident(&p.name.name)))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("{ret} {}({params})", c_fun_name(&f.name.name))
}

fn mangle_ident(name: &str) -> String {
    // avoid C keywords
    match name {
        "int" | "bool" | "return" | "if" | "else" | "while" | "void" | "main" => {
            format!("a_{name}")
        }
        _ => name.to_string(),
    }
}

fn emit_fun(out: &mut String, f: &FunDecl) {
    let _ = writeln!(out, "{} {{", c_fun_signature(f));
    emit_block(out, &f.body, 1);
    // ensure non-void without return gets a default (C)
    if f.return_type.is_some() && f.return_type.as_ref().map(|t| t.name.name.as_str()) != Some("Unit")
    {
        // if all paths return, compiler may warn; add unreachable fallback for Int/Bool
        match f.return_type.as_ref().map(|t| t.name.name.as_str()) {
            Some("Int") => {
                let _ = writeln!(out, "  return 0; /* fallback */");
            }
            Some("Bool") => {
                let _ = writeln!(out, "  return false; /* fallback */");
            }
            Some("String") => {
                let _ = writeln!(out, "  return \"\"; /* fallback */");
            }
            _ => {}
        }
    }
    let _ = writeln!(out, "}}");
}

fn emit_block(out: &mut String, block: &Block, indent: usize) {
    for stmt in &block.stmts {
        emit_stmt(out, stmt, indent);
    }
}

fn pad(n: usize) -> String {
    "  ".repeat(n)
}

fn emit_stmt(out: &mut String, stmt: &Stmt, indent: usize) {
    let p = pad(indent);
    match stmt {
        Stmt::Var(v) => {
            let ty = v
                .ty
                .as_ref()
                .map(c_type)
                .unwrap_or_else(|| infer_c_type_from_expr(&v.init));
            let _ = writeln!(
                out,
                "{p}{ty} {} = {};",
                mangle_ident(&v.name.name),
                emit_expr(&v.init)
            );
        }
        Stmt::If(i) => {
            let _ = writeln!(out, "{p}if ({}) {{", emit_expr(&i.cond));
            emit_block(out, &i.then_block, indent + 1);
            if let Some(else_b) = &i.else_block {
                let _ = writeln!(out, "{p}}} else {{");
                emit_block(out, else_b, indent + 1);
            }
            let _ = writeln!(out, "{p}}}");
        }
        Stmt::While(w) => {
            let _ = writeln!(out, "{p}while ({}) {{", emit_expr(&w.cond));
            emit_block(out, &w.body, indent + 1);
            let _ = writeln!(out, "{p}}}");
        }
        Stmt::Return(r) => match &r.value {
            None => {
                let _ = writeln!(out, "{p}return;");
            }
            Some(e) => {
                let _ = writeln!(out, "{p}return {};", emit_expr(e));
            }
        },
        Stmt::Expr(e) => {
            let _ = writeln!(out, "{p}{};", emit_expr(e));
        }
    }
}

fn infer_c_type_from_expr(e: &Expr) -> &'static str {
    match e {
        Expr::Int(_) => "int64_t",
        Expr::Bool(_) => "bool",
        Expr::String(_) | Expr::Null(_) => "const char *",
        Expr::Unary(UnaryExpr { op: UnOp::Neg, .. }) => "int64_t",
        Expr::Unary(UnaryExpr { op: UnOp::Not, .. }) => "bool",
        Expr::Binary(BinaryExpr {
            op: BinOp::Lt
                | BinOp::Le
                | BinOp::Gt
                | BinOp::Ge
                | BinOp::Eq
                | BinOp::Ne
                | BinOp::And
                | BinOp::Or,
            ..
        }) => "bool",
        Expr::Binary(_) => "int64_t",
        Expr::Call(_) => "int64_t",
        Expr::Assign(a) => infer_c_type_from_expr(&a.value),
        Expr::Group(inner, _) => infer_c_type_from_expr(inner),
        Expr::Ident(_) => "int64_t",
    }
}

fn emit_expr(expr: &Expr) -> String {
    match expr {
        Expr::Ident(i) => mangle_ident(&i.name),
        Expr::Int(n) => format!("INT64_C({})", n.value),
        Expr::Bool(b) => {
            if b.value {
                "true".into()
            } else {
                "false".into()
            }
        }
        Expr::String(s) => format!("\"{}\"", escape_c_string(&s.value)),
        Expr::Null(_) => "NULL".into(),
        Expr::Group(inner, _) => format!("({})", emit_expr(inner)),
        Expr::Unary(u) => {
            let op = match u.op {
                UnOp::Neg => "-",
                UnOp::Not => "!",
            };
            format!("({op}{})", emit_expr(&u.expr))
        }
        Expr::Binary(b) => {
            let op = match b.op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Rem => "%",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!("({} {} {})", emit_expr(&b.left), op, emit_expr(&b.right))
        }
        Expr::Assign(a) => {
            format!(
                "({} = {})",
                mangle_ident(&a.name.name),
                emit_expr(&a.value)
            )
        }
        Expr::Call(c) => {
            let name = match c.callee.as_ref() {
                Expr::Ident(id) => c_fun_name(&id.name),
                _ => "/*bad_call*/".into(),
            };
            let args = c
                .args
                .iter()
                .map(emit_expr)
                .collect::<Vec<_>>()
                .join(", ");
            format!("{name}({args})")
        }
    }
}

fn escape_c_string(s: &str) -> String {
    let mut out = String::new();
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_ascii_graphic() || c == ' ' => out.push(c),
            c => out.push_str(&format!("\\x{:02x}", c as u32)),
        }
    }
    out
}

/// Parse is caller's job; this typechecks then emits C.
pub fn emit_c_from_ast(file: &File) -> Result<String, CodegenError> {
    let checked = check_file(file)?;
    Ok(emit_c(&checked))
}

/// Typecheck + emit C + compile with the system C compiler (`CC` or `cc`).
pub fn build_from_file(
    file: &File,
    out_bin: &Path,
    runtime_c: &Path,
) -> Result<PathBuf, CodegenError> {
    let c_src = emit_c_from_ast(file)?;

    let parent = out_bin
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    fs::create_dir_all(&parent).map_err(|e| CodegenError::Io(e.to_string()))?;

    let c_path = parent.join(format!(
        "{}.aura.c",
        out_bin.file_name().and_then(|s| s.to_str()).unwrap_or("out")
    ));
    fs::write(&c_path, c_src).map_err(|e| CodegenError::Io(e.to_string()))?;

    let compiler = std::env::var("CC").unwrap_or_else(|_| "cc".into());
    let status = Command::new(&compiler)
        .arg("-O0")
        .arg("-std=c11")
        .arg(&c_path)
        .arg(runtime_c)
        .arg("-o")
        .arg(out_bin)
        .status()
        .map_err(|e| CodegenError::Compile(format!("failed to spawn {compiler}: {e}")))?;

    if !status.success() {
        return Err(CodegenError::Compile(format!(
            "{compiler} failed with status {status} (source {})",
            c_path.display()
        )));
    }

    Ok(out_bin.to_path_buf())
}
