//! Emit C99 for Aura C0–C2 programs and shell out to a C compiler.
//!
//! Classes → C structs; interfaces → tagged unions (closed-world dispatch).

use aura_ast::*;
use aura_sema::{check_file, CheckedFile, SemaError, Ty};
use std::collections::HashMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug)]
pub enum CodegenError {
    Sema(SemaError),
    Io(String),
    Compile(String),
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodegenError::Sema(e) => write!(f, "{e}"),
            CodegenError::Io(e) | CodegenError::Compile(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for CodegenError {}

impl From<SemaError> for CodegenError {
    fn from(e: SemaError) -> Self {
        CodegenError::Sema(e)
    }
}

struct EmitCtx<'a> {
    checked: &'a CheckedFile,
    /// Mono class key for `this` (e.g. `Box_String` or `User`).
    method_class: Option<&'a str>,
    type_params: Vec<String>,
    type_args: Vec<Ty>,
    /// Local name → type key (`Int`, `Box_String`, `Named`, …)
    locals: Vec<HashMap<String, String>>,
}

impl<'a> EmitCtx<'a> {
    fn push_scope(&mut self) {
        self.locals.push(HashMap::new());
    }

    fn pop_scope(&mut self) {
        self.locals.pop();
    }

    fn define_local(&mut self, name: &str, ty: String) {
        if let Some(scope) = self.locals.last_mut() {
            scope.insert(name.to_string(), ty);
        }
    }

    fn lookup_local(&self, name: &str) -> Option<&str> {
        for scope in self.locals.iter().rev() {
            if let Some(t) = scope.get(name) {
                return Some(t.as_str());
            }
        }
        None
    }
}

/// Emit a complete C translation unit for the checked file.
pub fn emit_c(checked: &CheckedFile) -> String {
    let mut out = String::new();
    out.push_str("/* generated by aura-codegen (C2 C backend) */\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("void aura_println(const char *s);\n");
    out.push_str("int aura_main(void);\n\n");

    // Stable class tags for interface dispatch (non-generic only)
    let tagged: Vec<_> = checked
        .ast
        .classes
        .iter()
        .filter(|c| c.type_params.is_empty())
        .collect();
    if !tagged.is_empty() {
        out.push_str("enum {\n");
        for (i, c) in tagged.iter().enumerate() {
            let _ = writeln!(out, "  AURA_TAG_{} = {},", c.name.name, i);
        }
        out.push_str("  AURA_TAG__COUNT\n};\n\n");
    }

    // Class typedefs — non-generic classes + monomorphized generic classes
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_typedef(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_typedef(&mut out, checked, c, args);
        }
    }

    // Interface tagged unions
    for iface in &checked.ast.interfaces {
        let impls = implementors(checked, &iface.name.name);
        let _ = writeln!(
            out,
            "typedef struct {} {{",
            c_iface_type(&iface.name.name)
        );
        out.push_str("  int tag;\n  union {\n");
        for c in &impls {
            let _ = writeln!(
                out,
                "    {} as_{};",
                c_class_type(&c.name.name),
                c.name.name
            );
        }
        if impls.is_empty() {
            out.push_str("    char _empty;\n");
        }
        let _ = writeln!(out, "  }} data;\n}} {};\n", c_iface_type(&iface.name.name));
    }

    // Forward decls
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_forwards(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_forwards(&mut out, checked, c, args);
        }
    }
    for iface in &checked.ast.interfaces {
        for m in &iface.methods {
            let _ = writeln!(
                out,
                "{};",
                c_iface_method_signature(&iface.name.name, m, checked)
            );
        }
    }
    for f in &checked.ast.functions {
        if f.name.name == "main" {
            continue;
        }
        if f.type_params.is_empty() {
            let _ = writeln!(out, "{};", c_fun_signature(f, checked, &[]));
        }
    }
    for (name, args) in &checked.mono_funs {
        if let Some(f) = checked.ast.functions.iter().find(|f| f.name.name == *name) {
            let _ = writeln!(out, "{};", c_fun_signature(f, checked, args));
        }
    }
    out.push('\n');

    // Definitions
    for c in &checked.ast.classes {
        if c.type_params.is_empty() {
            emit_class_defs(&mut out, checked, c, &[]);
        }
    }
    for (name, args) in &checked.mono_classes {
        if let Some(c) = checked.ast.classes.iter().find(|c| c.name.name == *name) {
            emit_class_defs(&mut out, checked, c, args);
        }
    }

    for iface in &checked.ast.interfaces {
        for m in &iface.methods {
            emit_iface_dispatch(&mut out, checked, &iface.name.name, m);
            out.push('\n');
        }
    }

    for f in &checked.ast.functions {
        if f.type_params.is_empty() {
            emit_fun(&mut out, f, checked, &[]);
            out.push('\n');
        }
    }
    for (name, args) in &checked.mono_funs {
        if let Some(f) = checked.ast.functions.iter().find(|f| f.name.name == *name) {
            emit_fun(&mut out, f, checked, args);
            out.push('\n');
        }
    }

    out.push_str("int aura_main(void) {\n");
    if checked.ast.functions.iter().any(|f| f.name.name == "main") {
        out.push_str("  aura_fn_main();\n");
    }
    out.push_str("  return 0;\n}\n");
    out
}

fn implementors<'a>(checked: &'a CheckedFile, iface: &str) -> Vec<&'a ClassDecl> {
    checked
        .ast
        .classes
        .iter()
        .filter(|c| c.implements.iter().any(|i| i.name == iface))
        .collect()
}

fn c_iface_type(name: &str) -> String {
    format!("aura_iface_{name}")
}

fn c_upcast_name(class: &str, iface: &str) -> String {
    format!("aura_upcast_{class}_to_{iface}")
}

fn c_iface_method_name(iface: &str, method: &str) -> String {
    format!("aura_iface_{iface}_{method}")
}

fn emit_upcast(out: &mut String, class: &str, iface: &str) {
    let _ = writeln!(
        out,
        "{} {}({} v) {{",
        c_iface_type(iface),
        c_upcast_name(class, iface),
        c_class_type(class)
    );
    let _ = writeln!(out, "  {} i;", c_iface_type(iface));
    let _ = writeln!(out, "  i.tag = AURA_TAG_{class};");
    let _ = writeln!(out, "  i.data.as_{class} = v;");
    out.push_str("  return i;\n}\n");
}

fn emit_iface_dispatch(
    out: &mut String,
    checked: &CheckedFile,
    iface: &str,
    m: &MethodSig,
) {
    let _ = writeln!(out, "{} {{", c_iface_method_signature(iface, m, checked));
    let ret = c_type_from_opt(&m.return_type, checked, &[], &[]);
    out.push_str("  switch (self->tag) {\n");
    for c in implementors(checked, iface) {
        let args = m
            .params
            .iter()
            .map(|p| mangle_ident(&p.name.name))
            .collect::<Vec<_>>();
        let call_args = if args.is_empty() {
            format!("&self->data.as_{}", c.name.name)
        } else {
            format!(
                "&self->data.as_{}, {}",
                c.name.name,
                args.join(", ")
            )
        };
        let mono = c.name.name.as_str();
        if ret == "void" {
            let _ = writeln!(
                out,
                "  case AURA_TAG_{}: {}({}); return;",
                c.name.name,
                c_method_name(mono, &m.name.name),
                call_args
            );
        } else {
            let _ = writeln!(
                out,
                "  case AURA_TAG_{}: return {}({});",
                c.name.name,
                c_method_name(mono, &m.name.name),
                call_args
            );
        }
    }
    out.push_str("  default:\n");
    if ret == "void" {
        out.push_str("    return;\n");
    } else if ret == "int64_t" {
        out.push_str("    return 0;\n");
    } else if ret == "bool" {
        out.push_str("    return false;\n");
    } else if ret == "const char *" {
        out.push_str("    return \"\";\n");
    } else {
        let _ = writeln!(out, "    return ({ret}){{0}};");
    }
    out.push_str("  }\n}\n");
}

fn c_iface_method_signature(iface: &str, m: &MethodSig, checked: &CheckedFile) -> String {
    let ret = c_type_from_opt(&m.return_type, checked, &[], &[]);
    let mut params = vec![format!("{} *self", c_iface_type(iface))];
    for p in &m.params {
        params.push(format!(
            "{} {}",
            c_type_ref(&p.ty, checked),
            mangle_ident(&p.name.name)
        ));
    }
    format!(
        "{ret} {}({})",
        c_iface_method_name(iface, &m.name.name),
        params.join(", ")
    )
}

fn mono_key(name: &str, args: &[Ty]) -> String {
    if args.is_empty() {
        name.to_string()
    } else {
        format!(
            "{}_{}",
            name,
            args.iter()
                .map(|a| a.mono_suffix())
                .collect::<Vec<_>>()
                .join("_")
        )
    }
}

fn c_class_type(mono: &str) -> String {
    format!("aura_cls_{mono}")
}

fn c_fun_name(name: &str, args: &[Ty]) -> String {
    if name == "main" {
        return "aura_fn_main".into();
    }
    if name == "println" {
        return "aura_println".into();
    }
    format!("aura_fn_{}", mono_key(name, args))
}

fn c_ctor_name(mono: &str) -> String {
    format!("aura_new_{mono}")
}

fn c_method_name(mono: &str, method: &str) -> String {
    format!("aura_method_{mono}_{method}")
}

fn subst_type_ref(ty: &TypeRef, params: &[String], args: &[Ty]) -> String {
    // Resolve type param names to concrete Ty display / mono
    if let Some(idx) = params.iter().position(|p| p == &ty.name.name) {
        if let Some(t) = args.get(idx) {
            return ty_to_c(t);
        }
    }
    if !ty.type_args.is_empty() {
        let mono = type_ref_mono(ty, params, args);
        if is_primitive_name(&ty.name.name) {
            return ty_to_c(&Ty::Class(ty.name.name.clone())); // shouldn't
        }
        return c_class_type(&mono);
    }
    match ty.name.name.as_str() {
        "Int" => "int64_t".into(),
        "Bool" => "bool".into(),
        "String" => "const char *".into(),
        "Unit" => "void".into(),
        name => c_class_type(name),
    }
}

fn is_primitive_name(n: &str) -> bool {
    matches!(n, "Int" | "Bool" | "String" | "Unit")
}

fn type_ref_mono(ty: &TypeRef, params: &[String], args: &[Ty]) -> String {
    if let Some(idx) = params.iter().position(|p| p == &ty.name.name) {
        if let Some(t) = args.get(idx) {
            return t.mono_suffix();
        }
    }
    if ty.type_args.is_empty() {
        ty.name.name.clone()
    } else {
        let a = ty
            .type_args
            .iter()
            .map(|t| type_ref_mono(t, params, args))
            .collect::<Vec<_>>()
            .join("_");
        format!("{}_{a}", ty.name.name)
    }
}

fn ty_to_c(t: &Ty) -> String {
    match t {
        Ty::Int => "int64_t".into(),
        Ty::Bool => "bool".into(),
        Ty::String => "const char *".into(),
        Ty::Unit => "void".into(),
        Ty::Null => "const char *".into(),
        Ty::Nullable(inner) => ty_to_c(inner),
        Ty::Class(n) => c_class_type(n),
        Ty::ClassApp { name, args } => c_class_type(&mono_key(name, args)),
        Ty::Interface(n) => c_iface_type(n),
        Ty::TypeParam(_) => "/* unbound T */ int64_t".into(),
    }
}

fn c_type_ref(ty: &TypeRef, checked: &CheckedFile) -> String {
    c_type_ref_subst(ty, checked, &[], &[])
}

fn c_type_ref_subst(
    ty: &TypeRef,
    checked: &CheckedFile,
    params: &[String],
    args: &[Ty],
) -> String {
    let _ = checked;
    if ty.nullable {
        // nullable class pointer not fully supported
        let inner = subst_type_ref(
            &TypeRef {
                nullable: false,
                ..ty.clone()
            },
            params,
            args,
        );
        if inner.starts_with("aura_cls_") {
            return format!("{inner} *");
        }
        return inner;
    }
    // interface?
    // handled via name
    if ty.type_args.is_empty() {
        if let Some(idx) = params.iter().position(|p| p == &ty.name.name) {
            if let Some(t) = args.get(idx) {
                return ty_to_c(t);
            }
        }
        match ty.name.name.as_str() {
            "Int" => "int64_t".into(),
            "Bool" => "bool".into(),
            "String" => "const char *".into(),
            "Unit" => "void".into(),
            name if checked.ast.interfaces.iter().any(|i| i.name.name == name) => {
                c_iface_type(name)
            }
            name => c_class_type(name),
        }
    } else {
        c_class_type(&type_ref_mono(ty, params, args))
    }
}

fn c_type_from_opt(ret: &Option<TypeRef>, checked: &CheckedFile, params: &[String], args: &[Ty]) -> String {
    match ret {
        None => "void".into(),
        Some(t) if t.name.name == "Unit" && t.type_args.is_empty() => "void".into(),
        Some(t) => c_type_ref_subst(t, checked, params, args),
    }
}

fn emit_class_typedef(out: &mut String, checked: &CheckedFile, c: &ClassDecl, args: &[Ty]) {
    let params: Vec<String> = c.type_params.iter().map(|p| p.name.clone()).collect();
    let mono = mono_key(&c.name.name, args);
    let _ = writeln!(out, "typedef struct {} {{", c_class_type(&mono));
    for f in &c.fields {
        let _ = writeln!(
            out,
            "  {} {};",
            c_type_ref_subst(&f.ty, checked, &params, args),
            mangle_ident(&f.name.name)
        );
    }
    if c.fields.is_empty() {
        out.push_str("  char _pad;\n");
    }
    let _ = writeln!(out, "}} {};\n", c_class_type(&mono));
}

fn emit_class_forwards(out: &mut String, checked: &CheckedFile, c: &ClassDecl, args: &[Ty]) {
    let params: Vec<String> = c.type_params.iter().map(|p| p.name.clone()).collect();
    let mono = mono_key(&c.name.name, args);
    let _ = writeln!(out, "{};", c_ctor_signature_mono(c, checked, &params, args, &mono));
    for m in &c.methods {
        let _ = writeln!(
            out,
            "{};",
            c_method_signature_mono(c, m, checked, &params, args, &mono)
        );
    }
    if args.is_empty() {
        for iface in &c.implements {
            let _ = writeln!(
                out,
                "{} {}({} v);",
                c_iface_type(&iface.name),
                c_upcast_name(&c.name.name, &iface.name),
                c_class_type(&mono)
            );
        }
    }
}

fn emit_class_defs(out: &mut String, checked: &CheckedFile, c: &ClassDecl, args: &[Ty]) {
    let params: Vec<String> = c.type_params.iter().map(|p| p.name.clone()).collect();
    let mono = mono_key(&c.name.name, args);
    emit_ctor_mono(out, c, checked, &params, args, &mono);
    out.push('\n');
    for m in &c.methods {
        emit_method_mono(out, c, m, checked, &params, args, &mono);
        out.push('\n');
    }
    if args.is_empty() {
        for iface in &c.implements {
            emit_upcast(out, &c.name.name, &iface.name);
            out.push('\n');
        }
    }
}

fn c_ctor_signature_mono(
    c: &ClassDecl,
    checked: &CheckedFile,
    params: &[String],
    args: &[Ty],
    mono: &str,
) -> String {
    let ret = c_class_type(mono);
    let ps = if c.fields.is_empty() {
        "void".into()
    } else {
        c.fields
            .iter()
            .map(|f| {
                format!(
                    "{} {}",
                    c_type_ref_subst(&f.ty, checked, params, args),
                    mangle_ident(&f.name.name)
                )
            })
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("{ret} {}({ps})", c_ctor_name(mono))
}

fn c_method_signature_mono(
    c: &ClassDecl,
    m: &FunDecl,
    checked: &CheckedFile,
    params: &[String],
    args: &[Ty],
    mono: &str,
) -> String {
    let _ = c;
    let ret = c_type_from_opt(&m.return_type, checked, params, args);
    let mut ps = vec![format!("{} *this", c_class_type(mono))];
    for p in &m.params {
        ps.push(format!(
            "{} {}",
            c_type_ref_subst(&p.ty, checked, params, args),
            mangle_ident(&p.name.name)
        ));
    }
    format!("{ret} {}({})", c_method_name(mono, &m.name.name), ps.join(", "))
}

fn c_fun_signature(f: &FunDecl, checked: &CheckedFile, args: &[Ty]) -> String {
    let params: Vec<String> = f.type_params.iter().map(|p| p.name.clone()).collect();
    let ret = c_type_from_opt(&f.return_type, checked, &params, args);
    let ps = if f.params.is_empty() {
        "void".into()
    } else {
        f.params
            .iter()
            .map(|p| {
                format!(
                    "{} {}",
                    c_type_ref_subst(&p.ty, checked, &params, args),
                    mangle_ident(&p.name.name)
                )
            })
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("{ret} {}({ps})", c_fun_name(&f.name.name, args))
}

fn emit_ctor_mono(
    out: &mut String,
    c: &ClassDecl,
    checked: &CheckedFile,
    params: &[String],
    args: &[Ty],
    mono: &str,
) {
    let _ = writeln!(
        out,
        "{} {{",
        c_ctor_signature_mono(c, checked, params, args, mono)
    );
    let _ = writeln!(out, "  {} self;", c_class_type(mono));
    for f in &c.fields {
        let n = mangle_ident(&f.name.name);
        let _ = writeln!(out, "  self.{n} = {n};");
    }
    out.push_str("  return self;\n}\n");
}

fn emit_method_mono(
    out: &mut String,
    c: &ClassDecl,
    m: &FunDecl,
    checked: &CheckedFile,
    params: &[String],
    args: &[Ty],
    mono: &str,
) {
    let _ = writeln!(
        out,
        "{} {{",
        c_method_signature_mono(c, m, checked, params, args, mono)
    );
    let mut ctx = EmitCtx {
        checked,
        method_class: Some(mono),
        type_params: params.to_vec(),
        type_args: args.to_vec(),
        locals: vec![HashMap::new()],
    };
    for f in &c.fields {
        ctx.define_local(&f.name.name, type_ref_local_key(&f.ty, params, args));
    }
    for p in &m.params {
        ctx.define_local(&p.name.name, type_ref_local_key(&p.ty, params, args));
    }
    emit_block(out, &m.body, 1, &mut ctx);
    emit_return_fallback(out, &m.return_type, checked, params, args);
    out.push_str("}\n");
}

fn mangle_ident(name: &str) -> String {
    match name {
        "int" | "bool" | "return" | "if" | "else" | "while" | "void" | "main" | "this" => {
            format!("a_{name}")
        }
        _ => name.to_string(),
    }
}

fn emit_fun(out: &mut String, f: &FunDecl, checked: &CheckedFile, args: &[Ty]) {
    let params: Vec<String> = f.type_params.iter().map(|p| p.name.clone()).collect();
    let _ = writeln!(out, "{} {{", c_fun_signature(f, checked, args));
    let mut ctx = EmitCtx {
        checked,
        method_class: None,
        type_params: params.clone(),
        type_args: args.to_vec(),
        locals: vec![HashMap::new()],
    };
    for p in &f.params {
        ctx.define_local(
            &p.name.name,
            type_ref_local_key(&p.ty, &params, args),
        );
    }
    emit_block(out, &f.body, 1, &mut ctx);
    emit_return_fallback(out, &f.return_type, checked, &params, args);
    out.push_str("}\n");
}

fn type_ref_local_key(ty: &TypeRef, params: &[String], args: &[Ty]) -> String {
    if let Some(idx) = params.iter().position(|p| p == &ty.name.name) {
        if let Some(t) = args.get(idx) {
            return match t {
                Ty::ClassApp { .. } | Ty::Class(_) => t.mono_suffix(),
                other => other.display(),
            };
        }
    }
    if ty.type_args.is_empty() {
        ty.name.name.clone()
    } else {
        type_ref_mono(ty, params, args)
    }
}

fn emit_return_fallback(
    out: &mut String,
    ret: &Option<TypeRef>,
    checked: &CheckedFile,
    params: &[String],
    args: &[Ty],
) {
    match ret {
        Some(t) if t.name.name != "Unit" || !t.type_args.is_empty() => {
            let ct = c_type_ref_subst(t, checked, params, args);
            if ct == "void" {
                return;
            }
            if ct == "int64_t" {
                out.push_str("  return 0; /* fallback */\n");
            } else if ct == "bool" {
                out.push_str("  return false; /* fallback */\n");
            } else if ct == "const char *" {
                out.push_str("  return \"\"; /* fallback */\n");
            } else if ct.starts_with("aura_cls_") {
                let _ = writeln!(out, "  return ({ct}){{0}}; /* fallback */");
            } else if ct.starts_with("aura_iface_") {
                let _ = writeln!(out, "  return ({ct}){{0}}; /* fallback */");
            }
        }
        _ => {}
    }
}

fn emit_block(out: &mut String, block: &Block, indent: usize, ctx: &mut EmitCtx<'_>) {
    ctx.push_scope();
    for stmt in &block.stmts {
        emit_stmt(out, stmt, indent, ctx);
    }
    ctx.pop_scope();
}

fn pad(n: usize) -> String {
    "  ".repeat(n)
}

fn emit_stmt(out: &mut String, stmt: &Stmt, indent: usize, ctx: &mut EmitCtx<'_>) {
    let p = pad(indent);
    match stmt {
        Stmt::Var(v) => {
            let ty_name = v
                .ty
                .as_ref()
                .map(|t| {
                    type_ref_local_key(t, &ctx.type_params, &ctx.type_args)
                })
                .unwrap_or_else(|| infer_type_name(&v.init, ctx));
            let ty = v
                .ty
                .as_ref()
                .map(|t| {
                    c_type_ref_subst(t, ctx.checked, &ctx.type_params, &ctx.type_args)
                })
                .unwrap_or_else(|| local_key_to_c(&ty_name, ctx.checked));
            ctx.define_local(&v.name.name, ty_name.clone());
            let init = coerce_expr(&v.init, &ty_name, ctx);
            let _ = writeln!(
                out,
                "{p}{ty} {} = {init};",
                mangle_ident(&v.name.name)
            );
        }
        Stmt::If(i) => {
            let _ = writeln!(out, "{p}if ({}) {{", emit_expr(&i.cond, ctx));
            emit_block(out, &i.then_block, indent + 1, ctx);
            if let Some(else_b) = &i.else_block {
                let _ = writeln!(out, "{p}}} else {{");
                emit_block(out, else_b, indent + 1, ctx);
            }
            let _ = writeln!(out, "{p}}}");
        }
        Stmt::While(w) => {
            let _ = writeln!(out, "{p}while ({}) {{", emit_expr(&w.cond, ctx));
            emit_block(out, &w.body, indent + 1, ctx);
            let _ = writeln!(out, "{p}}}");
        }
        Stmt::Return(r) => match &r.value {
            None => {
                let _ = writeln!(out, "{p}return;");
            }
            Some(e) => {
                let _ = writeln!(out, "{p}return {};", emit_expr(e, ctx));
            }
        },
        Stmt::Expr(e) => {
            let _ = writeln!(out, "{p}{};", emit_expr(e, ctx));
        }
    }
}

fn local_key_to_c(key: &str, checked: &CheckedFile) -> String {
    match key {
        "Int" => "int64_t".into(),
        "Bool" => "bool".into(),
        "String" => "const char *".into(),
        "Unit" => "void".into(),
        n if checked.ast.interfaces.iter().any(|i| i.name.name == n) => c_iface_type(n),
        n => c_class_type(n),
    }
}

fn infer_type_name(e: &Expr, ctx: &EmitCtx<'_>) -> String {
    match e {
        Expr::Int(_) => "Int".into(),
        Expr::Bool(_) => "Bool".into(),
        Expr::String(_) => "String".into(),
        Expr::Call(c) => match c.callee.as_ref() {
            Expr::Ident(id)
                if ctx
                    .checked
                    .ast
                    .classes
                    .iter()
                    .any(|x| x.name.name == id.name) =>
            {
                let targs: Vec<Ty> = ctx
                    .checked
                    .call_instantiations
                    .get(&c.span.start)
                    .map(|i| i.type_args.clone())
                    .unwrap_or_else(|| {
                        c.type_args
                            .iter()
                            .filter_map(|t| type_ref_to_ty(t, ctx))
                            .collect()
                    });
                mono_key(&id.name, &targs)
            }
            Expr::Ident(id)
                if ctx
                    .checked
                    .ast
                    .functions
                    .iter()
                    .any(|f| f.name.name == id.name) =>
            {
                let targs: Vec<Ty> = ctx
                    .checked
                    .call_instantiations
                    .get(&c.span.start)
                    .map(|i| i.type_args.clone())
                    .unwrap_or_else(|| {
                        c.type_args
                            .iter()
                            .filter_map(|t| type_ref_to_ty(t, ctx))
                            .collect()
                    });
                if let Some(f) = ctx
                    .checked
                    .ast
                    .functions
                    .iter()
                    .find(|f| f.name.name == id.name)
                {
                    let params: Vec<String> =
                        f.type_params.iter().map(|p| p.name.clone()).collect();
                    if let Some(rt) = &f.return_type {
                        return type_ref_local_key(rt, &params, &targs);
                    }
                }
                "Unit".into()
            }
            Expr::Field(fe) => {
                if let Some(mono) = resolve_class_of_expr(&fe.object, ctx) {
                    let base = mono_base_name(mono, ctx.checked).unwrap_or(mono);
                    if let Some(m) = ctx
                        .checked
                        .ast
                        .classes
                        .iter()
                        .find(|c| c.name.name == base)
                        .and_then(|c| c.methods.iter().find(|m| m.name.name == fe.field.name))
                    {
                        if let Some(rt) = &m.return_type {
                            // substitute class type args from mono key is hard; use name only for primitives
                            return type_ref_local_key(rt, &[], &[]);
                        }
                    }
                }
                "Int".into()
            }
            _ => "Int".into(),
        },
        Expr::Field(f) => {
            if let Some(mono) = resolve_class_of_expr(&f.object, ctx) {
                let base = mono_base_name(mono, ctx.checked).unwrap_or(mono);
                if let Some(field) = ctx
                    .checked
                    .ast
                    .classes
                    .iter()
                    .find(|c| c.name.name == base)
                    .and_then(|c| c.fields.iter().find(|x| x.name.name == f.field.name))
                {
                    return type_ref_local_key(&field.ty, &[], &[]);
                }
            }
            "String".into()
        }
        Expr::Ident(i) => ctx
            .lookup_local(&i.name)
            .unwrap_or("Int")
            .to_string(),
        Expr::This(_) => ctx.method_class.unwrap_or("Int").to_string(),
        Expr::Group(inner, _) => infer_type_name(inner, ctx),
        Expr::Assign(a) => infer_type_name(&a.value, ctx),
        Expr::Unary(UnaryExpr { op: UnOp::Not, .. }) => "Bool".into(),
        Expr::Binary(BinaryExpr {
            op: BinOp::Lt
                | BinOp::Le
                | BinOp::Gt
                | BinOp::Ge
                | BinOp::Eq
                | BinOp::Ne
                | BinOp::And
                | BinOp::Or,
            ..
        }) => "Bool".into(),
        _ => "Int".into(),
    }
}




fn emit_expr(expr: &Expr, ctx: &EmitCtx<'_>) -> String {
    match expr {
        Expr::Ident(i) => {
            // Inside method: bare field names → this->field
            if let Some(class) = ctx.method_class {
                if let Some(cl) = ctx.checked.ast.classes.iter().find(|c| c.name.name == class) {
                    if cl.fields.iter().any(|f| f.name.name == i.name) {
                        return format!("this->{}", mangle_ident(&i.name));
                    }
                }
            }
            mangle_ident(&i.name)
        }
        Expr::This(_) => "(*this)".into(),
        Expr::Int(n) => format!("INT64_C({})", n.value),
        Expr::Bool(b) => {
            if b.value {
                "true".into()
            } else {
                "false".into()
            }
        }
        Expr::String(s) => format!("\"{}\"", escape_c_string(&s.value)),
        Expr::Null(_) => "NULL".into(),
        Expr::Group(inner, _) => format!("({})", emit_expr(inner, ctx)),
        Expr::Unary(u) => {
            let op = match u.op {
                UnOp::Neg => "-",
                UnOp::Not => "!",
            };
            format!("({op}{})", emit_expr(&u.expr, ctx))
        }
        Expr::Binary(b) => {
            let op = match b.op {
                BinOp::Add => "+",
                BinOp::Sub => "-",
                BinOp::Mul => "*",
                BinOp::Div => "/",
                BinOp::Rem => "%",
                BinOp::Eq => "==",
                BinOp::Ne => "!=",
                BinOp::Lt => "<",
                BinOp::Le => "<=",
                BinOp::Gt => ">",
                BinOp::Ge => ">=",
                BinOp::And => "&&",
                BinOp::Or => "||",
            };
            format!(
                "({} {} {})",
                emit_expr(&b.left, ctx),
                op,
                emit_expr(&b.right, ctx)
            )
        }
        Expr::Assign(a) => {
            // field assign in method for bare field name
            let lhs = if let Some(class) = ctx.method_class {
                if let Some(cl) = ctx.checked.ast.classes.iter().find(|c| c.name.name == class) {
                    if cl.fields.iter().any(|f| f.name.name == a.name.name) {
                        format!("this->{}", mangle_ident(&a.name.name))
                    } else {
                        mangle_ident(&a.name.name)
                    }
                } else {
                    mangle_ident(&a.name.name)
                }
            } else {
                mangle_ident(&a.name.name)
            };
            format!("({lhs} = {})", emit_expr(&a.value, ctx))
        }
        Expr::Field(f) => {
            let obj = emit_expr(&f.object, ctx);
            // this.name already becomes (*this).name if object is This
            format!("({obj}).{}", mangle_ident(&f.field.name))
        }
        Expr::Call(c) => emit_call(c, ctx),
    }
}

fn emit_call(c: &CallExpr, ctx: &EmitCtx<'_>) -> String {
    // Method call: obj.method(args)
    if let Expr::Field(fe) = c.callee.as_ref() {
        let obj_ty = resolve_type_name(&fe.object, ctx);
        let obj = emit_expr(&fe.object, ctx);

        // Interface method
        if let Some(iface) = obj_ty.as_ref().filter(|t| {
            ctx.checked
                .ast
                .interfaces
                .iter()
                .any(|i| i.name.name == **t)
        }) {
            let mut args = vec![format!("&({obj})")];
            // param types from interface method
            if let Some(m) = ctx
                .checked
                .ast
                .interfaces
                .iter()
                .find(|i| i.name.name == *iface)
                .and_then(|i| i.methods.iter().find(|m| m.name.name == fe.field.name))
            {
                for (a, p) in c.args.iter().zip(m.params.iter()) {
                    args.push(coerce_expr(a, &p.ty.name.name, ctx));
                }
            } else {
                for a in &c.args {
                    args.push(emit_expr(a, ctx));
                }
            }
            return format!(
                "{}({})",
                c_iface_method_name(iface, &fe.field.name),
                args.join(", ")
            );
        }

        // Class method (obj_ty is mono key e.g. Box_String or User)
        let mono = obj_ty
            .as_deref()
            .or_else(|| resolve_class_of_expr(&fe.object, ctx))
            .unwrap_or("Unknown");
        let base = mono_base_name(mono, ctx.checked).unwrap_or(mono);
        let mut args = vec![format!("&({obj})")];
        if let Some(m) = ctx
            .checked
            .ast
            .classes
            .iter()
            .find(|c| c.name.name == base)
            .and_then(|c| c.methods.iter().find(|m| m.name.name == fe.field.name))
        {
            for (a, p) in c.args.iter().zip(m.params.iter()) {
                let expected = type_ref_local_key(&p.ty, &[], &[]);
                args.push(coerce_expr(a, &expected, ctx));
            }
        } else {
            for a in &c.args {
                args.push(emit_expr(a, ctx));
            }
        }
        return format!(
            "{}({})",
            c_method_name(mono, &fe.field.name),
            args.join(", ")
        );
    }

    match c.callee.as_ref() {
        Expr::Ident(id) => {
            // Prefer type args resolved by sema (explicit or inferred)
            let inst = ctx.checked.call_instantiations.get(&c.span.start);

            // Constructor (optional type args)
            if let Some(class) = ctx
                .checked
                .ast
                .classes
                .iter()
                .find(|x| x.name.name == id.name)
            {
                let targs: Vec<Ty> = if let Some(inst) = inst {
                    inst.type_args.clone()
                } else {
                    c.type_args
                        .iter()
                        .filter_map(|t| type_ref_to_ty(t, ctx))
                        .collect()
                };
                let mono = mono_key(&id.name, &targs);
                let params: Vec<String> =
                    class.type_params.iter().map(|p| p.name.clone()).collect();
                let args = c
                    .args
                    .iter()
                    .zip(class.fields.iter())
                    .map(|(a, f)| {
                        let expected = type_ref_local_key(&f.ty, &params, &targs);
                        coerce_expr(a, &expected, ctx)
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                return format!("{}({args})", c_ctor_name(&mono));
            }
            // Free function
            if let Some(f) = ctx
                .checked
                .ast
                .functions
                .iter()
                .find(|f| f.name.name == id.name)
            {
                let targs: Vec<Ty> = if let Some(inst) = inst {
                    inst.type_args.clone()
                } else {
                    c.type_args
                        .iter()
                        .filter_map(|t| type_ref_to_ty(t, ctx))
                        .collect()
                };
                let params: Vec<String> = f.type_params.iter().map(|p| p.name.clone()).collect();
                let args = c
                    .args
                    .iter()
                    .zip(f.params.iter())
                    .map(|(a, p)| {
                        let expected = type_ref_local_key(&p.ty, &params, &targs);
                        coerce_expr(a, &expected, ctx)
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                return format!("{}({args})", c_fun_name(&id.name, &targs));
            }
            let args = c
                .args
                .iter()
                .map(|a| emit_expr(a, ctx))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{}({args})", c_fun_name(&id.name, &[]))
        }
        _ => "/* bad call */(0)".into(),
    }
}

fn mono_base_name<'a>(mono: &'a str, checked: &'a CheckedFile) -> Option<&'a str> {
    if checked.ast.classes.iter().any(|c| c.name.name == mono) {
        return Some(mono);
    }
    for (name, args) in &checked.mono_classes {
        if mono_key(name, args) == mono {
            return Some(name.as_str());
        }
    }
    None
}

fn type_ref_to_ty(t: &TypeRef, ctx: &EmitCtx<'_>) -> Option<Ty> {
    if !t.type_args.is_empty() {
        let args: Vec<Ty> = t
            .type_args
            .iter()
            .filter_map(|a| type_ref_to_ty(a, ctx))
            .collect();
        return Some(Ty::ClassApp {
            name: t.name.name.clone(),
            args,
        });
    }
    match t.name.name.as_str() {
        "Int" => Some(Ty::Int),
        "Bool" => Some(Ty::Bool),
        "String" => Some(Ty::String),
        "Unit" => Some(Ty::Unit),
        name if ctx.checked.ast.classes.iter().any(|c| c.name.name == name) => {
            Some(Ty::Class(name.into()))
        }
        name if ctx
            .checked
            .ast
            .interfaces
            .iter()
            .any(|i| i.name.name == name) =>
        {
            Some(Ty::Interface(name.into()))
        }
        _ => None,
    }
}

/// If `expr` has class type `from` and expected is interface, emit upcast.
fn coerce_expr(expr: &Expr, expected_ty: &str, ctx: &EmitCtx<'_>) -> String {
    let actual = resolve_type_name(expr, ctx);
    let code = emit_expr(expr, ctx);
    if let Some(from) = actual {
        if from != expected_ty
            && ctx
                .checked
                .ast
                .interfaces
                .iter()
                .any(|i| i.name.name == expected_ty)
            && ctx
                .checked
                .ast
                .classes
                .iter()
                .any(|c| c.name.name == from && c.implements.iter().any(|i| i.name == expected_ty))
        {
            return format!("{}({code})", c_upcast_name(&from, expected_ty));
        }
    }
    // Constructor expr Greeter(...) inferred as class, expected interface
    if let Expr::Call(c) = expr {
        if let Expr::Ident(id) = c.callee.as_ref() {
            if ctx
                .checked
                .ast
                .classes
                .iter()
                .any(|cl| {
                    cl.name.name == id.name
                        && cl.implements.iter().any(|i| i.name == expected_ty)
                })
                && ctx
                    .checked
                    .ast
                    .interfaces
                    .iter()
                    .any(|i| i.name.name == expected_ty)
            {
                return format!("{}({code})", c_upcast_name(&id.name, expected_ty));
            }
        }
    }
    code
}

fn resolve_type_name(expr: &Expr, ctx: &EmitCtx<'_>) -> Option<String> {
    match expr {
        Expr::Ident(id) => ctx.lookup_local(&id.name).map(|s| s.to_string()),
        Expr::This(_) => ctx.method_class.map(|s| s.to_string()),
        Expr::Call(c) => {
            if let Expr::Ident(id) = c.callee.as_ref() {
                if ctx
                    .checked
                    .ast
                    .classes
                    .iter()
                    .any(|x| x.name.name == id.name)
                {
                    return Some(id.name.clone());
                }
                if let Some(f) = ctx
                    .checked
                    .ast
                    .functions
                    .iter()
                    .find(|f| f.name.name == id.name)
                {
                    return f.return_type.as_ref().map(|t| t.name.name.clone());
                }
            }
            if let Expr::Field(fe) = c.callee.as_ref() {
                // method return
                if let Some(recv) = resolve_type_name(&fe.object, ctx) {
                    if let Some(m) = ctx
                        .checked
                        .ast
                        .classes
                        .iter()
                        .find(|c| c.name.name == recv)
                        .and_then(|c| c.methods.iter().find(|m| m.name.name == fe.field.name))
                    {
                        return m.return_type.as_ref().map(|t| t.name.name.clone());
                    }
                    if let Some(m) = ctx
                        .checked
                        .ast
                        .interfaces
                        .iter()
                        .find(|i| i.name.name == recv)
                        .and_then(|i| i.methods.iter().find(|m| m.name.name == fe.field.name))
                    {
                        return m.return_type.as_ref().map(|t| t.name.name.clone());
                    }
                }
            }
            None
        }
        Expr::Field(f) => {
            let parent = resolve_type_name(&f.object, ctx)?;
            ctx.checked
                .ast
                .classes
                .iter()
                .find(|c| c.name.name == parent)
                .and_then(|c| c.fields.iter().find(|x| x.name.name == f.field.name))
                .map(|field| field.ty.name.name.clone())
        }
        Expr::Group(inner, _) => resolve_type_name(inner, ctx),
        Expr::String(_) => Some("String".into()),
        Expr::Int(_) => Some("Int".into()),
        Expr::Bool(_) => Some("Bool".into()),
        _ => None,
    }
}

/// Best-effort class name for method receiver (for mangling).
/// Returns mono class key for a receiver expression.
fn resolve_class_of_expr<'a>(expr: &Expr, ctx: &'a EmitCtx<'_>) -> Option<&'a str> {
    match expr {
        Expr::This(_) => ctx.method_class,
        Expr::Ident(id) => {
            let ty = ctx.lookup_local(&id.name)?;
            if ctx.checked.ast.classes.iter().any(|c| c.name.name == ty)
                || ctx
                    .checked
                    .mono_classes
                    .iter()
                    .any(|(n, a)| mono_key(n, a) == ty)
            {
                // Need to return ref into locals or mono list - use leak-free approach:
                // return from mono_classes storage
                return ctx.lookup_local(&id.name);
            }
            None
        }
        Expr::Call(c) => {
            if let Expr::Ident(id) = c.callee.as_ref() {
                if ctx
                    .checked
                    .ast
                    .classes
                    .iter()
                    .any(|x| x.name.name == id.name)
                {
                    // mono from type args — stored not as ref; fall back base name for non-generic
                    if c.type_args.is_empty() {
                        return ctx
                            .checked
                            .ast
                            .classes
                            .iter()
                            .find(|x| x.name.name == id.name)
                            .map(|x| x.name.name.as_str());
                    }
                    // For generic ctor, resolve_type_name is better
                    return None;
                }
            }
            None
        }
        Expr::Group(inner, _) => resolve_class_of_expr(inner, ctx),
        _ => None,
    }
}

fn escape_c_string(s: &str) -> String {
    let mut out = String::new();
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_ascii_graphic() || c == ' ' => out.push(c),
            c => out.push_str(&format!("\\x{:02x}", c as u32)),
        }
    }
    out
}

/// Parse is caller's job; this typechecks then emits C.
pub fn emit_c_from_ast(file: &File) -> Result<String, CodegenError> {
    let checked = check_file(file)?;
    Ok(emit_c(&checked))
}

/// Typecheck + emit C + compile with the system C compiler (`CC` or `cc`).
pub fn build_from_file(
    file: &File,
    out_bin: &Path,
    runtime_c: &Path,
) -> Result<PathBuf, CodegenError> {
    let c_src = emit_c_from_ast(file)?;

    let parent = out_bin
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    fs::create_dir_all(&parent).map_err(|e| CodegenError::Io(e.to_string()))?;

    let c_path = parent.join(format!(
        "{}.aura.c",
        out_bin.file_name().and_then(|s| s.to_str()).unwrap_or("out")
    ));
    fs::write(&c_path, c_src).map_err(|e| CodegenError::Io(e.to_string()))?;

    let compiler = std::env::var("CC").unwrap_or_else(|_| "cc".into());
    let status = Command::new(&compiler)
        .arg("-O0")
        .arg("-std=c11")
        .arg(&c_path)
        .arg(runtime_c)
        .arg("-o")
        .arg(out_bin)
        .status()
        .map_err(|e| CodegenError::Compile(format!("failed to spawn {compiler}: {e}")))?;

    if !status.success() {
        return Err(CodegenError::Compile(format!(
            "{compiler} failed with status {status} (source {})",
            c_path.display()
        )));
    }

    Ok(out_bin.to_path_buf())
}
