//! `aura new` / `aura init` package scaffolding (C11c).

use std::fs;
use std::path::{Path, PathBuf};

/// Scaffold a new package under `dir` (created if needed).
/// `pkg_name` is the Aura package name; `bin_name` is `[[bin]].name`.
pub fn scaffold_package(dir: &Path, pkg_name: &str, bin_name: &str) -> Result<(), String> {
    validate_package_name(pkg_name)?;
    validate_bin_name(bin_name)?;

    if dir.exists() {
        if !dir.is_dir() {
            return Err(format!(
                "error: `{}` exists and is not a directory",
                dir.display()
            ));
        }
        // Allow empty dir; reject if aura.toml or src already present.
        let toml = dir.join("aura.toml");
        let src = dir.join("src");
        if toml.exists() {
            return Err(format!(
                "error: package already exists (`{}`)",
                toml.display()
            ));
        }
        if src.exists() {
            return Err(format!(
                "error: `{}` already exists; refuse to overwrite",
                src.display()
            ));
        }
    } else {
        fs::create_dir_all(dir).map_err(|e| format!("error: create {}: {e}", dir.display()))?;
    }

    let src_dir = dir.join("src");
    fs::create_dir_all(&src_dir)
        .map_err(|e| format!("error: create {}: {e}", src_dir.display()))?;

    let toml = format!(
        "[package]\n\
         name = \"{pkg_name}\"\n\
         \n\
         [[bin]]\n\
         name = \"{bin_name}\"\n\
         path = \"src\"\n"
    );
    write_new(dir.join("aura.toml"), &toml)?;

    let main = format!(
        "// Generated by `aura new`\n\
         package {pkg_name}\n\
         \n\
         fun main() {{\n\
           println(\"Hello, Aura\")\n\
         }}\n"
    );
    write_new(src_dir.join("main.aura"), &main)?;

    Ok(())
}

fn write_new(path: PathBuf, contents: &str) -> Result<(), String> {
    if path.exists() {
        return Err(format!("error: `{}` already exists", path.display()));
    }
    fs::write(&path, contents).map_err(|e| format!("error: write {}: {e}", path.display()))
}

/// Validate Aura package name: dotted segments of `[A-Za-z_][A-Za-z0-9_]*`.
pub fn validate_package_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("error: package name must not be empty".into());
    }
    if name.starts_with('.') || name.ends_with('.') || name.contains("..") {
        return Err(format!("error: invalid package name `{name}`"));
    }
    for seg in name.split('.') {
        if seg.is_empty() {
            return Err(format!("error: invalid package name `{name}`"));
        }
        let mut chars = seg.chars();
        let Some(first) = chars.next() else {
            return Err(format!("error: invalid package name `{name}`"));
        };
        if !(first.is_ascii_alphabetic() || first == '_') {
            return Err(format!(
                "error: package segment `{seg}` must start with a letter or `_`"
            ));
        }
        if !chars.all(|c| c.is_ascii_alphanumeric() || c == '_') {
            return Err(format!(
                "error: package segment `{seg}` may only contain letters, digits, `_`"
            ));
        }
    }
    Ok(())
}

fn validate_bin_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("error: bin name must not be empty".into());
    }
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return Err("error: bin name must not be empty".into());
    };
    if !(first.is_ascii_alphanumeric() || first == '_') {
        return Err(format!("error: invalid bin name `{name}`"));
    }
    if !chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-') {
        return Err(format!("error: invalid bin name `{name}`"));
    }
    Ok(())
}

/// Derive package + bin names from a path or bare name argument.
pub fn names_from_arg(arg: &str) -> Result<(String, String), String> {
    let path = Path::new(arg);
    let stem = path
        .file_name()
        .and_then(|s| s.to_str())
        .filter(|s| !s.is_empty() && *s != "." && *s != "..")
        .ok_or_else(|| "error: could not derive package name from path".to_string())?;

    let pkg = sanitize_to_package(stem)?;
    let bin = sanitize_to_bin(stem)?;
    Ok((pkg, bin))
}

fn sanitize_to_package(stem: &str) -> Result<String, String> {
    let mut s = stem.replace('-', "_");
    // Drop characters that are not valid in a single package segment.
    s = s
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    while s.contains("__") {
        s = s.replace("__", "_");
    }
    let s = s.trim_matches('_').to_string();
    if s.is_empty() {
        return Err(format!("error: cannot derive package name from `{stem}`"));
    }
    // Must start with letter or underscore.
    let first = s.chars().next().unwrap();
    let s = if first.is_ascii_digit() {
        format!("p_{s}")
    } else {
        s
    };
    validate_package_name(&s)?;
    Ok(s)
}

fn sanitize_to_bin(stem: &str) -> Result<String, String> {
    let mut s: String = stem
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect();
    while s.contains("--") {
        s = s.replace("--", "-");
    }
    let s = s.trim_matches('-').to_string();
    if s.is_empty() {
        return Err(format!("error: cannot derive bin name from `{stem}`"));
    }
    validate_bin_name(&s)?;
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn package_name_ok() {
        validate_package_name("hello").unwrap();
        validate_package_name("demo.app").unwrap();
        validate_package_name("_x").unwrap();
    }

    #[test]
    fn package_name_bad() {
        assert!(validate_package_name("").is_err());
        assert!(validate_package_name("1bad").is_err());
        assert!(validate_package_name("a-b").is_err());
        assert!(validate_package_name(".x").is_err());
    }

    #[test]
    fn names_from_hyphen() {
        let (p, b) = names_from_arg("my-app").unwrap();
        assert_eq!(p, "my_app");
        assert_eq!(b, "my-app");
    }

    #[test]
    fn scaffold_roundtrip() {
        let n = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("aura-new-test-{n}"));
        let _ = fs::remove_dir_all(&dir);
        scaffold_package(&dir, "hello", "hello").unwrap();
        assert!(dir.join("aura.toml").is_file());
        assert!(dir.join("src/main.aura").is_file());
        let toml = fs::read_to_string(dir.join("aura.toml")).unwrap();
        assert!(toml.contains("name = \"hello\""));
        let src = fs::read_to_string(dir.join("src/main.aura")).unwrap();
        assert!(src.contains("package hello"));
        // Refuse overwrite.
        assert!(scaffold_package(&dir, "hello", "hello").is_err());
        let _ = fs::remove_dir_all(&dir);
    }
}
