name: Deploy Website

on:
  push:
    branches:
      - main
    paths:
      - "website/**"
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
          cache-dependency-path: website/yarn.lock
          registry-url: 'https://npm.pkg.github.com'
          scope: '@auraspace'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: website
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build website
        run: yarn build
        working-directory: website

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
